# This script
# First, extract the model parameters from the passed *.bestfit file
# Second, runs CLASS with those parameters to obtain:
#   - The scalar field evolution
#   - The scalar field potential evolution including the first and second derivatives
#   - The equation of state evolution of the scalar field
#   - The dark matter and dark energy density evolution
#   - The matter power spectrum P(k)
#   - The lensed CMB angular power spectrum C_ℓ
# Third, plots
#   - the de Sitter conjecture |dV|/V, |d^2V|/V, and the equation of state w as a function of redshift z
#   - the dark matter and dark energy density evolution as a function of redshift z
#   - the EoS evolution as a function of redshift z to check for phantom crossing
#   - 1+w-0.15s_1^2 as a function of redshift z to check for the swampland conjecture
#   - the matter power spectrum P(k) as a function of wavenumber k (log-log scale)
#   - the lensed CMB power spectrum C_ℓ (TT, EE, TE) as a function of multipole ℓ (log-log scale)

# Usage:
# python BestFitPlot.py --bestfit_file path/to/bestfit_file.bestfit --output_dir path/to/output_dir
# The bestfit_file should be a .bestfit file generated by the MCMC analysis, containing the best-fit parameters for the model.
# The output_dir is the directory where the plots will be saved.
# Default ouput dir is the current directory.
# --reuse_background can be used to skip rerunning CLASS and reuse existing output files and cache, e.g. to just regenerate the plots.

# 1. Extract the model parameters from the passed *.bestfit file

"""
BestFitPlot.py: Extract best-fit parameters from MCMC chains and prepare them for CLASS.

This script:
1. Extracts model parameters from a *.bestfit file (Cobaya output format)
2. Loads the corresponding *.input.yaml file (Cobaya MCMC configuration)
3. Maps Cobaya/MCMC parameter names to CLASS parameter names
4. Combines special parameters (e.g., scalar field parameters) into CLASS-compatible strings
5. Runs CLASS to compute background evolution, P(k), and C_ℓ outputs
6. Optionally loads LCDM baseline background data and computes Omega_cdm and Omega_λ
7. Generates five publication-quality plots:
   - Background evolution quantities (de Sitter parameters, energy densities, swampland)
   - Energy density plot with optional ΔΩ_cdm and ΔΩ_DE evolution (when LCDM baseline is provided)
   - Matter power spectrum P(k) with optional LCDM overlay
   - Lensed CMB power spectrum C_ℓ (TT, EE, TE modes) with optional LCDM overlay

Usage:

    # Basic usage: analyze model best-fit in current directory
    python BestFitPlot.py --bestfit_file /path/to/model.bestfit

    # Specify output directory
    python BestFitPlot.py --bestfit_file /path/to/model.bestfit --output_dir /path/to/output

    # Reuse existing CLASS outputs and cached data (fast iteration on plots)
    python BestFitPlot.py --bestfit_file /path/to/model.bestfit --reuse_background

    # Compare model against LCDM baseline:
    # - Runs CLASS for model best-fit parameters (or reuses if --reuse_background is set)
    # - Extracts LCDM background.dat and computes Omega_cdm^LCDM and Omega_λ^LCDM
    # - Overlays LCDM in P(k) and C_ℓ plots
    # - In energy density plot: adds lower panel showing ΔΩ_cdm and ΔΩ_DE evolution
    python BestFitPlot.py --bestfit_file /path/to/model.bestfit --lcdm_baseline /path/to/lcdm.bestfit --output_dir /path/to/output

Arguments:
    --bestfit_file BESTFIT_FILE
        Path to the .bestfit file (Cobaya MCMC output). Required.
        Must have a corresponding .input.yaml file with the same base name.

    --output_dir OUTPUT_DIR
        Directory where results and plots are saved (default: current directory).

    --reuse_background
        Skip running CLASS for the model and reuse existing output files and caches.
        Useful for iterating on plot aesthetics without recomputing CLASS spectra.

    --lcdm_baseline LCDM_BASELINE
        Optional path to an LCDM .bestfit file. When provided:
        - Generates or reuses LCDM background.dat, pk_matter.dat, cl_lensed.dat
        - Extracts Ω_cdm^LCDM and Ω_λ^LCDM from the LCDM background data
        - Computes ΔΩ_cdm = Ω_cdm^{model} - Ω_cdm^{LCDM}
        - Computes ΔΩ_DE = Ω_scf^{model} - Ω_λ^{LCDM}
        - Overlays LCDM curves in P(k) and C_ℓ plots
        - Extends energy-density plot (plot 2) into a two-panel figure:
          * Upper panel: model Ω_scf and Ω_cdm (unchanged from single-panel case)
          * Middle axis: shared redshift z scale
          * Lower panel: ΔΩ_cdm and ΔΩ_DE evolution with reference at Δ=0

Output Files:
    For each plot, three formats are generated: PNG, PDF, PGF
    - plot1_*: de Sitter parameters (s_1, s_2)
    - plot2_*: Energy densities (Ω_scf, Ω_cdm; or with ΔΩ panel if --lcdm_baseline is set)
    - plot3_*: Swampland expression (1+w-0.15s₁²) and equation of state (w)
    - plot4_*: Matter power spectrum P(k) [+ LCDM overlay if --lcdm_baseline]
    - plot5_*: Lensed CMB power spectrum C_ℓ (TT, EE, TE) [+ LCDM overlay if --lcdm_baseline]

    Plus cache files for fast reruns:
    - *.processed.npz: cached CLASS output datasets
    - *.lcdm_omegas.processed.npz: cached LCDM Omega_cdm and Omega_lambda values
"""

import argparse
import os
import re
import subprocess
import sys
from zipfile import BadZipFile
from pathlib import Path
from typing import Dict, Any, Tuple, List, Optional

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import yaml
from matplotlib.axes import Axes
from matplotlib.figure import Figure
from matplotlib.ticker import FixedFormatter, FixedLocator, NullFormatter

_LCDM_BASELINE_INPUT_KEYS = (
    "n_s",
    "H0",
    "tau_reio",
    "omega_b",
    "omega_cdm",
    "m_ncdm",
    "A_s",
    "Omega_Lambda",
)

_DISALLOWED_LCDM_KEYS = {
    "Omega_scf",
    "Omega_fld",
    "scf_potential",
    "scf_parameters",
    "scf_tuning_index",
    "attractor_ic_scf",
    "model_cdm",
    "cdm_c",
}


def parse_arguments() -> argparse.Namespace:
    """Parse command-line arguments for BestFitPlot.

    Returns:
        argparse.Namespace: Parsed arguments with 'bestfit_file' and 'output_dir'
    """
    parser = argparse.ArgumentParser(
        description="Extract CLASS parameters from Cobaya MCMC best-fit files"
    )
    parser.add_argument(
        "--bestfit_file",
        type=str,
        required=True,
        help="Path to the .bestfit file (Cobaya MCMC output)",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default=".",
        help="Output directory for results (default: current directory)",
    )
    parser.add_argument(
        "--reuse_background",
        action="store_true",
        help=(
            "Reuse existing CLASS outputs (background, P(k), C_ℓ) and cache files instead of rerunning CLASS. "
            "Useful while iterating on plotting aesthetics."
        ),
    )
    parser.add_argument(
        "--lcdm_baseline",
        type=str,
        default=None,
        help=(
            "Optional path to an LCDM .bestfit file. When provided, the script generates/reuses "
            "LCDM background/P(k)/lensed C_ℓ outputs and overlays LCDM references in the P(k) and C_ℓ plots."
        ),
    )
    return parser.parse_args()


def load_bestfit_file(bestfit_path: str) -> Dict[str, float]:
    """Parse a Cobaya .bestfit file and extract parameter values.

    The .bestfit file format contains lines with:
        index  value  parameter_name  LaTeX_description

    Parameters starting with '#' are ignored (comment lines).

    Args:
        bestfit_path: Path to the .bestfit file

    Returns:
        Dictionary mapping parameter names to their float values

    Raises:
        FileNotFoundError: If the file does not exist
        ValueError: If the file format is invalid
    """
    if not os.path.exists(bestfit_path):
        raise FileNotFoundError(f"Best-fit file not found: {bestfit_path}")

    parameters = {}
    with open(bestfit_path, "r") as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()

            # Skip empty lines and comments
            if not line or line.startswith("#") or line.startswith("-"):
                continue

            # Parse the line: index  value  parameter_name  LaTeX_description
            parts = line.split()
            if len(parts) < 3:
                continue

            try:
                # Extract index, value, and parameter name
                value = float(parts[1])
                param_name = parts[2]

                # Store the parameter
                parameters[param_name] = value
            except (ValueError, IndexError):
                # Skip lines that don't match the expected format
                continue

    if not parameters:
        raise ValueError(f"No parameters found in file: {bestfit_path}")

    return parameters


def load_input_yaml(yaml_path: str) -> Dict[str, Any]:
    """Load a Cobaya .input.yaml file (MCMC configuration).

    Args:
        yaml_path: Path to the .input.yaml file

    Returns:
        Parsed YAML dictionary

    Raises:
        FileNotFoundError: If the file does not exist
        yaml.YAMLError: If the YAML is invalid
    """
    if not os.path.exists(yaml_path):
        raise FileNotFoundError(f"Input YAML file not found: {yaml_path}")

    with open(yaml_path, "r") as f:
        config = yaml.safe_load(f)

    return config


def find_input_yaml(bestfit_path: str) -> str:
    """Find the corresponding .input.yaml file for a .bestfit file.

    Assumes the .input.yaml file has the same name as .bestfit but with
    ".input.yaml" extension instead of ".bestfit".

    Args:
        bestfit_path: Path to the .bestfit file

    Returns:
        Path to the corresponding .input.yaml file

    Raises:
        FileNotFoundError: If the .input.yaml file is not found
    """
    base_path = bestfit_path.rsplit(".bestfit", 1)[0]
    yaml_path = f"{base_path}.input.yaml"

    if not os.path.exists(yaml_path):
        raise FileNotFoundError(
            f"Could not find corresponding YAML file: {yaml_path}\n"
            f"Expected base name: {base_path}"
        )

    return yaml_path


# List of all known CLASS input parameters
# This is used to filter out derived and output parameters from YAML specifications
_CLASS_INPUT_PARAMETERS = {
    # Cosmological parameters - standard
    "H0",
    "h",
    "theta_s_100",
    "omega_b",
    "Omega_b",
    "omega_cdm",
    "Omega_cdm",
    "Omega_k",
    "Omega_Lambda",
    "Omega_fld",
    "Omega_scf",
    "T_cmb",
    "YHe",
    "recombination",
    # Primordial perturbations
    "n_s",
    "alpha_s",
    "A_s",
    "k_pivot",
    # Reionization
    "z_reio",
    "tau_reio",
    "reio_parametrization",
    "reionization_exponent",
    "reionization_width",
    "helium_fullreio_redshift",
    "helium_fullreio_width",
    # Neutrino/relativistic species
    "N_ur",
    "N_ncdm",
    "m_ncdm",
    "omega_ncdm",
    "Omega_ncdm",
    "deg_ncdm",
    "sBBN file",
    # Dark energy - fluid
    "w0_fld",
    "wa_fld",
    "cs2_fld",
    "fluid_equation_of_state",
    "Omega_EDE",
    # Scalar field dark energy
    "scf_potential",
    "scf_parameters",
    "scf_tuning_index",
    "attractor_ic_scf",
    # Interacting dark matter (custom extension)
    "model_cdm",
    "cdm_c",
    # Output options
    "output",
    "modes",
    "ic",
    "gauge",
    "non_linear",
    "l_max_scalars",
    "l_max_tensors",
    "l_max_lss",
    "P_k_max_h/Mpc",
    "P_k_max_1/Mpc",
    "k_output_values",
    "z_pk",
    "number_count_contributions",
    "selection",
    "selection_mean",
    "selection_width",
    "tensor_method",
    "perturbations_verbose",
    "background_verbose",
    "input_verbose",
    "thermodynamics_verbose",
    "lensing_verbose",
    "transfer_verbose",
    "primordial_verbose",
    "harmonic_verbose",
    "fourier_verbose",
    "output_verbose",
    # Energy injection
    "DM_annihilation_cross_section",
    "DM_annihilation_mass",
    "DM_decay_fraction",
    "DM_decay_Gamma",
    # Precision/computation options
    "compute_damping_scale",
    "varying_fundamental_constants",
}

# Parameters that can appear in chains as derived/reporting outputs but are not
# valid CLASS input keys.
_NON_INPUT_PARAMETERS = {
    "cdm_f_phi0",
}


def extract_class_parameters(
    bestfit_values: Dict[str, float], yaml_config: Dict[str, Any]
) -> Dict[str, Any]:
    """Map Cobaya MCMC parameters to CLASS input parameters.

    This function:
    1. Extracts parameters marked as drop: false and derived: false (or no 'derived' key)
    2. Handles special scalar field parameters that need to be combined into 'scf_parameters'
    3. Includes extra_args from the YAML theory.classy section
    4. Filters to only include known CLASS input parameters

    Args:
        bestfit_values: Parameter values extracted from .bestfit file
        yaml_config: Parsed YAML configuration from .input.yaml

    Returns:
        Dictionary ready to pass to classy.set(), with CLASS parameter names and values

    Raises:
        KeyError: If required sections are missing from the YAML
        ValueError: If parameter extraction fails
    """
    class_params = {}

    # 1. Extract theory.classy.extra_args (these are trusted CLASS inputs)
    if "theory" in yaml_config and "classy" in yaml_config["theory"]:
        classy_config = yaml_config["theory"]["classy"]
        if "extra_args" in classy_config:
            class_params.update(classy_config["extra_args"])

    # 2. Extract primary (non-dropped, non-derived) parameters from params section
    if "params" not in yaml_config:
        raise KeyError("'params' section not found in YAML configuration")

    params_config = yaml_config["params"]
    dropped_scf_params = {}  # Store dropped scalar field parameters for recombination

    for param_name, param_spec in params_config.items():
        if param_name in _NON_INPUT_PARAMETERS:
            continue

        # Skip output/tracking parameters that are not CLASS inputs
        if param_name not in _CLASS_INPUT_PARAMETERS and not param_name.startswith(
            "scf_"
        ):
            continue

        # Skip if parameter specification is a scalar value (like Omega_fld = 0.0)
        if not isinstance(param_spec, dict):
            # Handle direct scalar assignments (e.g., Omega_fld: 0.0)
            if param_name in _CLASS_INPUT_PARAMETERS:
                class_params[param_name] = param_spec
            continue

        # Determine if this parameter should be included in CLASS input
        is_dropped = param_spec.get("drop", False)
        has_derived = "derived" in param_spec

        # Special handling for scf_parameters: it should be constructed, not directly copied
        if param_name == "scf_parameters":
            # This will be handled separately after collecting all needed parameters
            continue

        # Extract parameter value from bestfit if it exists
        if param_name in bestfit_values:
            value = bestfit_values[param_name]

            # Collect dropped scalar field parameters for later recombination
            if is_dropped and param_name.startswith("scf_"):
                dropped_scf_params[param_name] = value

            # Include parameter if:
            # 1. It's not dropped and not derived, OR
            # 2. It's a dropped scalar field parameter (for later reconstruction)
            if not is_dropped and not has_derived:
                class_params[param_name] = value
            elif is_dropped and param_name.startswith("scf_"):
                # Keep dropped scalar field params for reconstruction
                dropped_scf_params[param_name] = value
        elif not is_dropped and not has_derived and param_name in params_config:
            # If parameter spec has a 'value' field, use it
            if isinstance(param_spec, dict) and "value" in param_spec:
                class_params[param_name] = param_spec["value"]

    # 3. Reconstruct scf_parameters from individual components
    if dropped_scf_params and "chi_ini" in bestfit_values:
        class_params["scf_parameters"] = _construct_scf_parameters(
            dropped_scf_params=dropped_scf_params,
            bestfit_values=bestfit_values,
            yaml_config=yaml_config,
        )

    # 4. CLASS expects yes/no strings for boolean-like flags.
    for key, value in list(class_params.items()):
        if isinstance(value, bool):
            class_params[key] = "yes" if value else "no"

    return class_params


def _construct_scf_parameters(
    dropped_scf_params: Dict[str, float],
    bestfit_values: Dict[str, float],
    yaml_config: Dict[str, Any],
) -> str:
    """Construct the scf_parameters string from individual scalar field parameters.

    The scf_parameters string is a comma-separated list of CLASS scalar field parameters
    in the order: c1, c2, c3, c4, q1, q2, q3, q4, exp1, exp2, phi_ini, phi_prime_ini

        Values are resolved with the following precedence:
            1. Explicit value present in the .bestfit file (preferred)
            2. Value captured in dropped_scf_params
            3. Literal YAML default value (if provided)
            4. Fallback to 0.0

        This precedence is important because some chains provide derived scf_* entries
        (e.g. scf_c1, scf_phi_ini) in the .bestfit file without a literal YAML value.

    Args:
        dropped_scf_params: Individual scalar field parameters from .bestfit
        bestfit_values: All parameter values from .bestfit
        yaml_config: YAML configuration for extracting default values if needed

    Returns:
        A comma-separated string of scalar field parameters for CLASS
    """
    # Define the expected order of parameters in scf_parameters
    scf_param_order = [
        "scf_c1",
        "scf_c2",
        "scf_c3",
        "scf_c4",
        "scf_q1",
        "scf_q2",
        "scf_q3",
        "scf_q4",
        "scf_exp1",
        "scf_exp2",
        "scf_phi_ini",
        "scf_phi_prime_ini",
    ]

    scf_values = []

    for scf_param in scf_param_order:
        # Prefer the actual best-fit number when available.
        if scf_param in bestfit_values:
            scf_values.append(str(bestfit_values[scf_param]))
            continue

        # Fall back to collected dropped entries.
        if scf_param in dropped_scf_params:
            scf_values.append(str(dropped_scf_params[scf_param]))
            continue

        # Fall back to literal YAML defaults when provided.
        if (
            "params" in yaml_config
            and scf_param in yaml_config["params"]
            and isinstance(yaml_config["params"][scf_param], dict)
            and "value" in yaml_config["params"][scf_param]
        ):
            scf_values.append(str(yaml_config["params"][scf_param]["value"]))
            continue

        # Last resort fallback.
        scf_values.append("0.0")

    return ",".join(scf_values)


def extract_parameters_from_bestfit(
    bestfit_path: str, yaml_path: Optional[str] = None
) -> Tuple[Dict[str, Any], Dict[str, Any]]:
    """Main function: Extract CLASS parameters from Cobaya best-fit and YAML files.

    This is the primary entry point that orchestrates the entire parameter extraction process.

    Args:
        bestfit_path: Path to the .bestfit file
        yaml_path: Path to the .input.yaml file (auto-detected if None)

    Returns:
        Tuple containing:
            - Dictionary of CLASS parameters ready for classy.set()
            - Dictionary of extraction metadata and warnings

    Raises:
        FileNotFoundError: If required files are not found
        ValueError: If extraction fails

    Example:
        >>> class_params, metadata = extract_parameters_from_bestfit(
        ...     'hyperbolic_Planck_InitCond_MCMC.bestfit'
        ... )
        >>> print(class_params)
        {'H0': 67.32, 'n_s': 0.964, ..., 'scf_parameters': '1.037e-07,0.5,0.0,...'}
    """
    # Find YAML file if not provided
    if yaml_path is None:
        yaml_path = find_input_yaml(bestfit_path)

    # Load files
    bestfit_values = load_bestfit_file(bestfit_path)
    yaml_config = load_input_yaml(yaml_path)

    # Extract CLASS parameters
    class_params = extract_class_parameters(bestfit_values, yaml_config)

    # Prepare metadata
    metadata = {
        "bestfit_file": os.path.abspath(bestfit_path),
        "yaml_file": os.path.abspath(yaml_path),
        "parameters_extracted": len(class_params),
        "warnings": [],
    }

    return class_params, metadata


def extract_lcdm_baseline_parameters(
    bestfit_path: str, yaml_path: Optional[str] = None
) -> Tuple[Dict[str, Any], Dict[str, Any]]:
    """Extract a minimal CLASS parameter set for an LCDM baseline run."""
    if yaml_path is None:
        yaml_path = find_input_yaml(bestfit_path)

    bestfit_values = load_bestfit_file(bestfit_path)
    yaml_config = load_input_yaml(yaml_path)

    class_params: Dict[str, Any] = {}

    if "theory" in yaml_config and "classy" in yaml_config["theory"]:
        classy_config = yaml_config["theory"]["classy"]
        if "extra_args" in classy_config and isinstance(
            classy_config["extra_args"], dict
        ):
            class_params.update(classy_config["extra_args"])

    for key in _LCDM_BASELINE_INPUT_KEYS:
        if key in bestfit_values:
            class_params[key] = bestfit_values[key]

    # Recover A_s when only logA is present.
    if "A_s" not in class_params and "logA" in bestfit_values:
        class_params["A_s"] = 1e-10 * np.exp(bestfit_values["logA"])

    for forbidden in _DISALLOWED_LCDM_KEYS:
        class_params.pop(forbidden, None)

    for key, value in list(class_params.items()):
        if isinstance(value, bool):
            class_params[key] = "yes" if value else "no"

    metadata = {
        "bestfit_file": os.path.abspath(bestfit_path),
        "yaml_file": os.path.abspath(yaml_path),
        "parameters_extracted": len(class_params),
        "warnings": [],
    }

    return class_params, metadata


def _build_output_paths(bestfit_path: str, output_dir: str) -> Dict[str, str]:
    """Build canonical output paths for a best-fit file label."""
    run_label = Path(bestfit_path).name.replace(".bestfit", "")
    output_root = Path(output_dir).expanduser().resolve() / run_label

    return {
        "output_root": str(output_root),
        "background_file": str(Path(f"{output_root}_background.dat")),
        "pk_file": str(Path(f"{output_root}_pk.dat")),
        "cl_lensed_file": str(Path(f"{output_root}_cl_lensed.dat")),
    }


def resolve_or_run_class_outputs(
    class_params: Dict[str, Any],
    bestfit_path: str,
    output_dir: str,
    *,
    reuse_only: bool,
    reuse_if_available: bool,
) -> Dict[str, str]:
    """Resolve CLASS outputs by reusing existing files or running CLASS as needed."""
    candidate = _build_output_paths(bestfit_path=bestfit_path, output_dir=output_dir)
    bg_ok = Path(candidate["background_file"]).exists()
    pk_ok = Path(candidate["pk_file"]).exists()
    cl_ok = Path(candidate["cl_lensed_file"]).exists()
    all_ok = bg_ok and pk_ok and cl_ok

    if reuse_only:
        if not all_ok:
            raise FileNotFoundError(
                "--reuse_background was set but one or more output files do not exist:\n"
                f"  Background: {bg_ok}\n"
                f"  P(k):       {pk_ok}\n"
                f"  C_ℓ:        {cl_ok}"
            )
        return {
            "class_executable": str(Path(__file__).resolve().parents[1] / "class"),
            "generated_ini": "(reused)",
            "output_root": candidate["output_root"],
            "background_file": candidate["background_file"],
            "pk_file": candidate["pk_file"],
            "cl_lensed_file": candidate["cl_lensed_file"],
            "run_source": "reused",
        }

    if reuse_if_available and all_ok:
        return {
            "class_executable": str(Path(__file__).resolve().parents[1] / "class"),
            "generated_ini": "(reused)",
            "output_root": candidate["output_root"],
            "background_file": candidate["background_file"],
            "pk_file": candidate["pk_file"],
            "cl_lensed_file": candidate["cl_lensed_file"],
            "run_source": "reused",
        }

    run_info = run_class_background(
        class_params=class_params,
        bestfit_path=bestfit_path,
        output_dir=output_dir,
    )
    run_info["run_source"] = "computed"
    return run_info


def _serialize_class_value(value: Any) -> str:
    """Serialize a Python value into a CLASS .ini-compatible value string."""
    if isinstance(value, bool):
        return "yes" if value else "no"
    if value is None:
        return ""
    return str(value)


# 2.a) Run CLASS with the extracted parameters to obtain the background data.


def run_class_background(
    class_params: Dict[str, Any],
    bestfit_path: str,
    output_dir: str,
) -> Dict[str, str]:
    """Run CLASS with extracted parameters to generate background, P(k), and C_ℓ outputs.

        This function creates an auto-generated CLASS .ini file, requests:
            - write_background = yes
            - output = tCl,lCl,mPk
    and runs CLASS to generate all three data files. Returns paths to all generated files.

    Args:
        class_params: Dictionary of CLASS parameters from step 1.
        bestfit_path: Path to source best-fit file, used to derive output names.
        output_dir: Directory where generated .ini and CLASS outputs are written.

    Returns:
        Dict containing:
            - class_executable
            - generated_ini
            - background_file
            - pk_file
            - cl_lensed_file
            - output_root

    Raises:
        FileNotFoundError: If CLASS executable is missing.
        RuntimeError: If CLASS execution fails.
    """
    repo_root = Path(__file__).resolve().parents[1]
    class_executable = repo_root / "class"

    if not class_executable.exists():
        raise FileNotFoundError(
            f"CLASS executable not found at: {class_executable}. Build it with 'make class -j'."
        )

    out_dir = Path(output_dir).expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    run_label = Path(bestfit_path).name.replace(".bestfit", "")
    output_root = out_dir / run_label
    ini_path = out_dir / f"{run_label}_autogen.ini"

    # Request background, P(k), and lensed C_ℓ outputs with deterministic overwrite.
    run_params = dict(class_params)
    run_params["write_background"] = "yes"
    # For lensed TT/EE/TE spectra, CLASS requires tCl (or pCl) and lCl.
    run_params["output"] = "tCl,lCl,mPk"
    run_params["lensing"] = "yes"
    if "modes" not in run_params or not str(run_params["modes"]).strip():
        run_params["modes"] = "s"
    run_params["overwrite_root"] = "yes"
    run_params["root"] = str(output_root)
    # Ensure non_linear is set to allow P(k) computation.
    # If not present in class_params, default to halofit.
    if "non linear" not in run_params or not run_params["non linear"]:
        run_params["non linear"] = "halofit"

    # Normalize sBBN file path when only a bare filename is provided in YAML.
    # CLASS concatenates base_path + sBBN file, so we need a relative subpath.
    sbbn_key = "sBBN file"
    if sbbn_key in run_params:
        sbbn_value = str(run_params[sbbn_key]).strip()
        if sbbn_value and "/" not in sbbn_value and "\\" not in sbbn_value:
            run_params[sbbn_key] = f"/external/bbn/{sbbn_value}"
        elif sbbn_value.startswith("bbn/"):
            run_params[sbbn_key] = f"/external/{sbbn_value}"

    with open(ini_path, "w") as f:
        f.write("# Auto-generated by BestFitPlot.py\n")
        f.write(f"# Source bestfit: {bestfit_path}\n\n")
        for key in sorted(run_params.keys()):
            f.write(f"{key} = {_serialize_class_value(run_params[key])}\n")

    run_result = subprocess.run(
        [str(class_executable), str(ini_path)],
        cwd=str(repo_root),
        capture_output=True,
        text=True,
    )

    background_file = Path(f"{output_root}_background.dat")
    pk_file = Path(f"{output_root}_pk.dat")
    cl_lensed_file = Path(f"{output_root}_cl_lensed.dat")

    if run_result.returncode != 0:
        stdout_tail = "\n".join(run_result.stdout.splitlines()[-30:])
        stderr_tail = "\n".join(run_result.stderr.splitlines()[-30:])
        raise RuntimeError(
            "CLASS run failed.\n"
            f"Return code: {run_result.returncode}\n"
            f"Generated ini: {ini_path}\n"
            f"--- STDOUT (tail) ---\n{stdout_tail}\n"
            f"--- STDERR (tail) ---\n{stderr_tail}"
        )

    if not background_file.exists():
        raise RuntimeError(
            "CLASS run completed but background file was not found.\n"
            f"Expected: {background_file}\n"
            f"Generated ini: {ini_path}"
        )

    if not pk_file.exists():
        raise RuntimeError(
            "CLASS run completed but P(k) file was not found.\n"
            f"Expected: {pk_file}\n"
            f"Generated ini: {ini_path}"
        )

    if not cl_lensed_file.exists():
        raise RuntimeError(
            "CLASS run completed but lensed C_l file was not found.\n"
            f"Expected: {cl_lensed_file}\n"
            f"Generated ini: {ini_path}"
        )

    return {
        "class_executable": str(class_executable),
        "generated_ini": str(ini_path),
        "background_file": str(background_file),
        "pk_file": str(pk_file),
        "cl_lensed_file": str(cl_lensed_file),
        "output_root": str(output_root),
    }


# 2.b) Extract the background data from the stored file and compute quantities
#      Obtain the scalar field evolution, the scalar field potential evolution including the first and second derivatives,
#      the equation of state evolution of the scalar field, and the dark matter and dark energy density evolution from CLASS
#      We extract
#      - the redhisft z
#      - the dark matter density rho_cdm
#      - the dark energy density rho_scf
#      - the critical density rho_crit
#      - the scalar field pressur p_scf
#      - the scalar field potential V
#      - the scalar field potential first derivative dV
#      - the scalar field potential second derivative d2V
#      Based on these quantities, we then compute
#      - the equation of state w = p_scf / rho_scf
#      - the de Sitter conjecture s1=|dV|/V and -s2=d^2V/V
#      - the swampland conjecture 1+w-0.15s1^2
#      - the relative energy densities Omega_cdm = rho_cdm / rho_crit and Omega_scf = rho_scf / rho_crit


def _parse_background_column_labels(background_file: str) -> List[str]:
    """Parse the CLASS background header and return column labels in order."""
    header_line = None
    with open(background_file, "r") as f:
        for line in f:
            if line.startswith("#") and "1:z" in line:
                header_line = line.lstrip("#").strip()
                break

    if header_line is None:
        raise ValueError(
            f"Could not find CLASS background column header in: {background_file}"
        )

    # Capture chunks like "1:z", "2:proper time [Gyr]", ...
    matches = re.findall(r"(\d+):(.*?)(?=(?:\s+\d+:)|$)", header_line)
    if not matches:
        raise ValueError(f"Failed to parse header labels in: {background_file}")

    # Sort by index and strip text
    ordered = sorted(
        ((int(i), label.strip()) for i, label in matches), key=lambda x: x[0]
    )
    return [label for _, label in ordered]


def _find_column_index(labels: List[str], required_label: str) -> int:
    """Find exact column label index or raise a clear error."""
    try:
        return labels.index(required_label)
    except ValueError as exc:
        raise KeyError(
            f"Required background column '{required_label}' not found. Available labels: {labels}"
        ) from exc


def _compute_background_derived(
    *,
    z: np.ndarray,
    rho_cdm: np.ndarray,
    rho_scf: np.ndarray,
    rho_crit: np.ndarray,
    p_scf: np.ndarray,
    V: np.ndarray,
    dV: np.ndarray,
    d2V: np.ndarray,
) -> Dict[str, np.ndarray]:
    """Compute derived background quantities from primitive arrays."""
    with np.errstate(divide="ignore", invalid="ignore"):
        a = 1.0 / (1.0 + z)
        w = np.where(rho_scf != 0.0, p_scf / rho_scf, np.nan)
        s1 = np.where(V != 0.0, np.abs(dV) / V, np.nan)
        minus_s2 = np.where(V != 0.0, d2V / V, np.nan)
        Omega_cdm = np.where(rho_crit != 0.0, rho_cdm / rho_crit, np.nan)
        Omega_scf = np.where(rho_crit != 0.0, rho_scf / rho_crit, np.nan)

    return {
        "a": a,
        "w": w,
        "s1": s1,
        "minus_s2": minus_s2,
        "swampland_expr": 1.0 + w - 0.15 * np.square(s1),
        "Omega_cdm": Omega_cdm,
        "Omega_scf": Omega_scf,
    }


def load_background_dataset(background_file: str) -> Dict[str, Any]:
    """Load CLASS background file, extract required columns, and compute derived quantities.

    Extracted columns:
      - z
      - (.)rho_cdm
      - (.)rho_scf
      - (.)rho_crit
      - (.)p_scf
      - V_scf
      - V'_scf
      - V''_scf

    Computed quantities:
      - a = 1/(1+z)
      - w = p_scf / rho_scf
      - s1 = |V'_scf| / V_scf
      - minus_s2 = V''_scf / V_scf
      - swampland_expr = 1 + w - 0.15 * s1^2
      - Omega_cdm = rho_cdm / rho_crit
      - Omega_scf = rho_scf / rho_crit
    """
    labels = _parse_background_column_labels(background_file)
    data = np.loadtxt(background_file, comments="#")

    if data.ndim == 1:
        data = data[np.newaxis, :]

    idx = {
        "z": _find_column_index(labels, "z"),
        "rho_cdm": _find_column_index(labels, "(.)rho_cdm"),
        "rho_scf": _find_column_index(labels, "(.)rho_scf"),
        "rho_crit": _find_column_index(labels, "(.)rho_crit"),
        "p_scf": _find_column_index(labels, "(.)p_scf"),
        "V": _find_column_index(labels, "V_scf"),
        "dV": _find_column_index(labels, "V'_scf"),
        "d2V": _find_column_index(labels, "V''_scf"),
    }

    z = data[:, idx["z"]]
    rho_cdm = data[:, idx["rho_cdm"]]
    rho_scf = data[:, idx["rho_scf"]]
    rho_crit = data[:, idx["rho_crit"]]
    p_scf = data[:, idx["p_scf"]]
    V = data[:, idx["V"]]
    dV = data[:, idx["dV"]]
    d2V = data[:, idx["d2V"]]

    derived = _compute_background_derived(
        z=z,
        rho_cdm=rho_cdm,
        rho_scf=rho_scf,
        rho_crit=rho_crit,
        p_scf=p_scf,
        V=V,
        dV=dV,
        d2V=d2V,
    )

    return {
        "background_file": background_file,
        "column_labels": labels,
        "column_indices": idx,
        "raw_table": data,
        "z": z,
        "rho_cdm": rho_cdm,
        "rho_scf": rho_scf,
        "rho_crit": rho_crit,
        "p_scf": p_scf,
        "V": V,
        "dV": dV,
        "d2V": d2V,
        **derived,
    }


def _background_cache_needs_rewrite(
    schema_version: int,
    cached: Any,
    derived: Dict[str, np.ndarray],
) -> bool:
    """Return whether a loaded background cache should be rewritten.

    Older cache files can contain stale derived arrays even when their
    primitive columns are still correct. Rewriting normalizes them to the
    current schema and avoids repeatedly carrying forward inconsistent values.
    """
    if schema_version < 2:
        return True

    for key, derived_array in derived.items():
        if key not in cached.files:
            return True

        cached_array = cached[key]
        if cached_array.shape != derived_array.shape:
            return True

        if not np.allclose(cached_array, derived_array, equal_nan=True):
            return True

    return False


def save_background_dataset_cache(dataset: Dict[str, Any], cache_file: str) -> None:
    """Save processed background dataset to a compressed NPZ cache file."""
    path = Path(cache_file)
    path.parent.mkdir(parents=True, exist_ok=True)

    column_label_array = np.array(dataset["column_labels"], dtype=str)
    column_index_keys = np.array(list(dataset["column_indices"].keys()), dtype=str)
    column_index_values = np.array(
        list(dataset["column_indices"].values()), dtype=np.int64
    )

    np.savez_compressed(
        str(path),
        schema_version=np.array([2], dtype=np.int64),
        background_file=np.array([str(dataset["background_file"])], dtype=str),
        column_labels=column_label_array,
        column_index_keys=column_index_keys,
        column_index_values=column_index_values,
        raw_table=dataset["raw_table"],
        z=dataset["z"],
        a=dataset["a"],
        rho_cdm=dataset["rho_cdm"],
        rho_scf=dataset["rho_scf"],
        rho_crit=dataset["rho_crit"],
        p_scf=dataset["p_scf"],
        V=dataset["V"],
        dV=dataset["dV"],
        d2V=dataset["d2V"],
        w=dataset["w"],
        s1=dataset["s1"],
        minus_s2=dataset["minus_s2"],
        swampland_expr=dataset["swampland_expr"],
        Omega_cdm=dataset["Omega_cdm"],
        Omega_scf=dataset["Omega_scf"],
    )


def load_background_dataset_cache(cache_file: str) -> Dict[str, Any]:
    """Load processed background dataset from a compressed NPZ cache file."""
    with np.load(cache_file, allow_pickle=False) as cached:
        schema_version = int(cached["schema_version"][0])
        if schema_version not in (1, 2):
            raise ValueError(
                f"Unsupported background cache schema version: {schema_version}"
            )

        background_file = str(cached["background_file"][0])
        cached_column_labels = [str(x) for x in cached["column_labels"].tolist()]
        cached_column_index_keys = [
            str(x) for x in cached["column_index_keys"].tolist()
        ]
        cached_column_index_values = [
            int(x) for x in cached["column_index_values"].tolist()
        ]
        cached_column_indices = dict(
            zip(cached_column_index_keys, cached_column_index_values)
        )

        raw_table = cached["raw_table"]
        if os.path.exists(background_file):
            column_labels = _parse_background_column_labels(background_file)
            column_indices = {
                "z": _find_column_index(column_labels, "z"),
                "rho_cdm": _find_column_index(column_labels, "(.)rho_cdm"),
                "rho_scf": _find_column_index(column_labels, "(.)rho_scf"),
                "rho_crit": _find_column_index(column_labels, "(.)rho_crit"),
                "p_scf": _find_column_index(column_labels, "(.)p_scf"),
                "V": _find_column_index(column_labels, "V_scf"),
                "dV": _find_column_index(column_labels, "V'_scf"),
                "d2V": _find_column_index(column_labels, "V''_scf"),
            }
        else:
            column_labels = cached_column_labels
            column_indices = cached_column_indices

        z = raw_table[:, column_indices["z"]]
        rho_cdm = raw_table[:, column_indices["rho_cdm"]]
        rho_scf = raw_table[:, column_indices["rho_scf"]]
        rho_crit = raw_table[:, column_indices["rho_crit"]]
        p_scf = raw_table[:, column_indices["p_scf"]]
        V = raw_table[:, column_indices["V"]]
        dV = raw_table[:, column_indices["dV"]]
        d2V = raw_table[:, column_indices["d2V"]]
        derived = _compute_background_derived(
            z=z,
            rho_cdm=rho_cdm,
            rho_scf=rho_scf,
            rho_crit=rho_crit,
            p_scf=p_scf,
            V=V,
            dV=dV,
            d2V=d2V,
        )
        cache_needs_rewrite = (
            _background_cache_needs_rewrite(schema_version, cached, derived)
            or column_labels != cached_column_labels
            or column_indices != cached_column_indices
        )

        return {
            "background_file": background_file,
            "column_labels": column_labels,
            "column_indices": column_indices,
            "raw_table": raw_table,
            "z": z,
            "rho_cdm": rho_cdm,
            "rho_scf": rho_scf,
            "rho_crit": rho_crit,
            "p_scf": p_scf,
            "V": V,
            "dV": dV,
            "d2V": d2V,
            "_cache_needs_rewrite": cache_needs_rewrite,
            **derived,
        }


def load_or_compute_background_dataset(
    background_file: str,
    cache_file: Optional[str] = None,
) -> Tuple[Dict[str, Any], str]:
    """Load processed dataset from cache when valid; otherwise compute and cache.

    Returns:
        (dataset, source) where source is one of: "cache" or "computed".
    """
    if cache_file is None:
        cache_file = str(Path(background_file).with_suffix(".processed.npz"))

    bg_path = Path(background_file)
    cache_path = Path(cache_file)

    if cache_path.exists() and cache_path.stat().st_mtime >= bg_path.stat().st_mtime:
        try:
            dataset = load_background_dataset_cache(str(cache_path))
            cache_needs_rewrite = bool(dataset.pop("_cache_needs_rewrite", False))
            if cache_needs_rewrite:
                save_background_dataset_cache(dataset, str(cache_path))
            return dataset, "cache"
        except (KeyError, ValueError, OSError, EOFError, BadZipFile):
            pass

    dataset = load_background_dataset(background_file)
    save_background_dataset_cache(dataset, str(cache_path))
    return dataset, "computed"


def load_lcdm_background_omegas_dataset(background_file: str) -> Dict[str, Any]:
    """Load LCDM background file and compute Omega_cdm and Omega_lambda."""
    labels = _parse_background_column_labels(background_file)
    data = np.loadtxt(background_file, comments="#")

    if data.ndim == 1:
        data = data[np.newaxis, :]

    idx = {
        "z": _find_column_index(labels, "z"),
        "rho_cdm": _find_column_index(labels, "(.)rho_cdm"),
        "rho_lambda": _find_column_index(labels, "(.)rho_lambda"),
        "rho_crit": _find_column_index(labels, "(.)rho_crit"),
    }

    z = data[:, idx["z"]]
    rho_cdm = data[:, idx["rho_cdm"]]
    rho_lambda = data[:, idx["rho_lambda"]]
    rho_crit = data[:, idx["rho_crit"]]

    with np.errstate(divide="ignore", invalid="ignore"):
        Omega_cdm = np.where(rho_crit != 0.0, rho_cdm / rho_crit, np.nan)
        Omega_lambda = np.where(rho_crit != 0.0, rho_lambda / rho_crit, np.nan)

    return {
        "background_file": background_file,
        "column_labels": labels,
        "column_indices": idx,
        "raw_table": data,
        "z": z,
        "rho_cdm": rho_cdm,
        "rho_lambda": rho_lambda,
        "rho_crit": rho_crit,
        "Omega_cdm": Omega_cdm,
        "Omega_lambda": Omega_lambda,
    }


def save_lcdm_background_omegas_cache(dataset: Dict[str, Any], cache_file: str) -> None:
    """Save processed LCDM Omega dataset to a compressed NPZ cache file."""
    path = Path(cache_file)
    path.parent.mkdir(parents=True, exist_ok=True)

    column_label_array = np.array(dataset["column_labels"], dtype=str)
    column_index_keys = np.array(list(dataset["column_indices"].keys()), dtype=str)
    column_index_values = np.array(
        list(dataset["column_indices"].values()), dtype=np.int64
    )

    np.savez_compressed(
        str(path),
        schema_version=np.array([1], dtype=np.int64),
        background_file=np.array([str(dataset["background_file"])], dtype=str),
        column_labels=column_label_array,
        column_index_keys=column_index_keys,
        column_index_values=column_index_values,
        raw_table=dataset["raw_table"],
        z=dataset["z"],
        rho_cdm=dataset["rho_cdm"],
        rho_lambda=dataset["rho_lambda"],
        rho_crit=dataset["rho_crit"],
        Omega_cdm=dataset["Omega_cdm"],
        Omega_lambda=dataset["Omega_lambda"],
    )


def load_lcdm_background_omegas_cache(cache_file: str) -> Dict[str, Any]:
    """Load processed LCDM Omega dataset from a compressed NPZ cache file."""
    with np.load(cache_file, allow_pickle=False) as cached:
        schema_version = int(cached["schema_version"][0])
        if schema_version != 1:
            raise ValueError(
                f"Unsupported LCDM Omega cache schema version: {schema_version}"
            )

        column_labels = [str(x) for x in cached["column_labels"].tolist()]
        column_index_keys = [str(x) for x in cached["column_index_keys"].tolist()]
        column_index_values = [int(x) for x in cached["column_index_values"].tolist()]
        column_indices = dict(zip(column_index_keys, column_index_values))

        return {
            "background_file": str(cached["background_file"][0]),
            "column_labels": column_labels,
            "column_indices": column_indices,
            "raw_table": cached["raw_table"],
            "z": cached["z"],
            "rho_cdm": cached["rho_cdm"],
            "rho_lambda": cached["rho_lambda"],
            "rho_crit": cached["rho_crit"],
            "Omega_cdm": cached["Omega_cdm"],
            "Omega_lambda": cached["Omega_lambda"],
        }


def load_or_compute_lcdm_background_omegas_dataset(
    background_file: str,
    cache_file: Optional[str] = None,
) -> Tuple[Dict[str, Any], str]:
    """Load LCDM Omega dataset from cache when valid; otherwise compute and cache."""
    if cache_file is None:
        cache_file = f"{background_file}.lcdm_omegas.processed.npz"

    bg_path = Path(background_file)
    cache_path = Path(cache_file)

    if cache_path.exists() and cache_path.stat().st_mtime >= bg_path.stat().st_mtime:
        dataset = load_lcdm_background_omegas_cache(str(cache_path))
        return dataset, "cache"

    dataset = load_lcdm_background_omegas_dataset(background_file)
    save_lcdm_background_omegas_cache(dataset, str(cache_path))
    return dataset, "computed"


# 2.c) Extract P(k) power spectrum data.


def load_pk_dataset(pk_file: str) -> Dict[str, Any]:
    """Load CLASS P(k) file and extract k and P(k) values.

    Extracts:
      - k (wavenumber in h/Mpc)
      - P_k (matter power spectrum in (Mpc/h)^3)

    Args:
        pk_file: Path to the CLASS *_pk.dat file

    Returns:
        Dictionary containing:
            - k: wavenumber array
            - P_k: power spectrum array
            - pk_file: source file path
    """
    if not Path(pk_file).exists():
        raise FileNotFoundError(f"P(k) file not found: {pk_file}")

    data = np.loadtxt(pk_file, comments="#")

    if data.ndim == 1:
        data = data[np.newaxis, :]

    # CLASS P(k) file format: k, P(k)
    # First column is k, second is P(k)
    if data.shape[1] < 2:
        raise ValueError(f"P(k) file has insufficient columns: {data.shape}")

    k = data[:, 0]
    P_k = data[:, 1]

    return {
        "pk_file": pk_file,
        "k": k,
        "P_k": P_k,
    }


def save_pk_dataset_cache(dataset: Dict[str, Any], cache_file: str) -> None:
    """Save processed P(k) dataset to a compressed NPZ cache file."""
    path = Path(cache_file)
    path.parent.mkdir(parents=True, exist_ok=True)

    np.savez_compressed(
        str(path),
        schema_version=np.array([1], dtype=np.int64),
        pk_file=np.array([str(dataset["pk_file"])], dtype=str),
        k=dataset["k"],
        P_k=dataset["P_k"],
    )


def load_pk_dataset_cache(cache_file: str) -> Dict[str, Any]:
    """Load processed P(k) dataset from a compressed NPZ cache file."""
    with np.load(cache_file, allow_pickle=False) as cached:
        schema_version = int(cached["schema_version"][0])
        if schema_version != 1:
            raise ValueError(f"Unsupported P(k) cache schema version: {schema_version}")

        return {
            "pk_file": str(cached["pk_file"][0]),
            "k": cached["k"],
            "P_k": cached["P_k"],
        }


def load_or_compute_pk_dataset(
    pk_file: str,
    cache_file: Optional[str] = None,
) -> Tuple[Dict[str, Any], str]:
    """Load processed P(k) dataset from cache when valid; otherwise compute and cache.

    Returns:
        (dataset, source) where source is one of: "cache" or "computed".
    """
    if cache_file is None:
        cache_file = str(Path(pk_file).with_suffix(".processed.npz"))

    pk_path = Path(pk_file)
    cache_path = Path(cache_file)

    if cache_path.exists() and cache_path.stat().st_mtime >= pk_path.stat().st_mtime:
        dataset = load_pk_dataset_cache(str(cache_path))
        return dataset, "cache"

    dataset = load_pk_dataset(pk_file)
    save_pk_dataset_cache(dataset, str(cache_path))
    return dataset, "computed"


# 2.d) Extract C_ℓ lensed power spectrum data.


def load_cl_dataset(cl_lensed_file: str, lmax: int = 9000) -> Dict[str, Any]:
    """Load CLASS lensed C_ℓ file and extract ℓ and C_ℓ values for TT, EE, TE.

    Extracts:
      - ell (multipole moments)
      - ell * (ell + 1) / (2 * pi) * C_ℓ^TT (scaled TT power)
      - ell * (ell + 1) / (2 * pi) * C_ℓ^EE (scaled EE power)
      - ell * (ell + 1) / (2 * pi) * C_ℓ^TE (scaled TE power)

    Args:
        cl_lensed_file: Path to the CLASS *_cl_lensed.dat file
        lmax: Maximum multipole to retain (default: 9000)

    Returns:
        Dictionary containing:
            - ell: multipole array
            - ell_times_ell_plus_1_over_2pi: scaling factor ℓ(ℓ+1)/(2π)
            - Cl_TT_scaled: scaled TT power
            - Cl_EE_scaled: scaled EE power
            - Cl_TE_scaled: scaled TE power
            - cl_lensed_file: source file path
    """
    if not Path(cl_lensed_file).exists():
        raise FileNotFoundError(f"C_ℓ file not found: {cl_lensed_file}")

    data = np.loadtxt(cl_lensed_file, comments="#")

    if data.ndim == 1:
        data = data[np.newaxis, :]

    # CLASS lensed C_ℓ file format: ell, TT, EE, TE, BB
    # First column is ell, then TT, EE, TE, BB (if present)
    if data.shape[1] < 4:
        raise ValueError(f"C_ℓ file has insufficient columns: {data.shape}")

    ell = data[:, 0].astype(int)
    Cl_TT = data[:, 1]
    Cl_EE = data[:, 2]
    Cl_TE = data[:, 3]

    # Filter to lmax and apply scaling ℓ(ℓ+1)/(2π)
    mask = ell <= lmax
    ell = ell[mask]
    Cl_TT = Cl_TT[mask]
    Cl_EE = Cl_EE[mask]
    Cl_TE = Cl_TE[mask]

    # Scale by ℓ(ℓ+1)/(2π) for standard power units
    scaling = ell * (ell + 1.0) / (2.0 * np.pi)
    Cl_TT_scaled = scaling * Cl_TT
    Cl_EE_scaled = scaling * Cl_EE
    Cl_TE_scaled = scaling * Cl_TE

    return {
        "cl_lensed_file": cl_lensed_file,
        "ell": ell,
        "ell_times_ell_plus_1_over_2pi": scaling,
        "Cl_TT_scaled": Cl_TT_scaled,
        "Cl_EE_scaled": Cl_EE_scaled,
        "Cl_TE_scaled": Cl_TE_scaled,
    }


def save_cl_dataset_cache(dataset: Dict[str, Any], cache_file: str) -> None:
    """Save processed C_ℓ dataset to a compressed NPZ cache file."""
    path = Path(cache_file)
    path.parent.mkdir(parents=True, exist_ok=True)

    requested_lmax = dataset.get("requested_lmax")
    if requested_lmax is None:
        raise ValueError("C_ℓ cache save requires 'requested_lmax' in dataset")

    np.savez_compressed(
        str(path),
        schema_version=np.array([2], dtype=np.int64),
        cl_lensed_file=np.array([str(dataset["cl_lensed_file"])], dtype=str),
        requested_lmax=np.array([int(requested_lmax)], dtype=np.int64),
        ell=dataset["ell"],
        ell_times_ell_plus_1_over_2pi=dataset["ell_times_ell_plus_1_over_2pi"],
        Cl_TT_scaled=dataset["Cl_TT_scaled"],
        Cl_EE_scaled=dataset["Cl_EE_scaled"],
        Cl_TE_scaled=dataset["Cl_TE_scaled"],
    )


def load_cl_dataset_cache(
    cache_file: str,
    requested_lmax: Optional[int] = None,
) -> Dict[str, Any]:
    """Load processed C_ℓ dataset from a compressed NPZ cache file."""
    with np.load(cache_file, allow_pickle=False) as cached:
        schema_version = int(cached["schema_version"][0])
        if schema_version not in (1, 2):
            raise ValueError(f"Unsupported C_ℓ cache schema version: {schema_version}")

        if schema_version == 2:
            cache_lmax = int(cached["requested_lmax"][0])
        else:
            # Legacy schema has no explicit lmax metadata; infer from stored ell grid.
            cache_lmax = int(np.max(cached["ell"])) if cached["ell"].size else -1

        cache_needs_rewrite = schema_version < 2
        if requested_lmax is not None and cache_lmax != int(requested_lmax):
            raise ValueError(
                f"C_ℓ cache lmax mismatch: cache={cache_lmax}, requested={requested_lmax}"
            )

        return {
            "cl_lensed_file": str(cached["cl_lensed_file"][0]),
            "requested_lmax": cache_lmax,
            "ell": cached["ell"],
            "ell_times_ell_plus_1_over_2pi": cached["ell_times_ell_plus_1_over_2pi"],
            "Cl_TT_scaled": cached["Cl_TT_scaled"],
            "Cl_EE_scaled": cached["Cl_EE_scaled"],
            "Cl_TE_scaled": cached["Cl_TE_scaled"],
            "_cache_needs_rewrite": cache_needs_rewrite,
        }


def load_or_compute_cl_dataset(
    cl_lensed_file: str,
    cache_file: Optional[str] = None,
    lmax: int = 9000,
) -> Tuple[Dict[str, Any], str]:
    """Load processed C_ℓ dataset from cache when valid; otherwise compute and cache.

    Returns:
        (dataset, source) where source is one of: "cache" or "computed".
    """
    if cache_file is None:
        cache_file = str(Path(cl_lensed_file).with_suffix(".processed.npz"))

    cl_path = Path(cl_lensed_file)
    cache_path = Path(cache_file)

    if cache_path.exists() and cache_path.stat().st_mtime >= cl_path.stat().st_mtime:
        try:
            dataset = load_cl_dataset_cache(
                str(cache_path),
                requested_lmax=lmax,
            )
            cache_needs_rewrite = bool(dataset.pop("_cache_needs_rewrite", False))
            if cache_needs_rewrite:
                save_cl_dataset_cache(dataset, str(cache_path))
            return dataset, "cache"
        except (KeyError, ValueError, OSError, EOFError, BadZipFile):
            pass

    dataset = load_cl_dataset(cl_lensed_file, lmax=lmax)
    dataset["requested_lmax"] = int(lmax)
    save_cl_dataset_cache(dataset, str(cache_path))
    return dataset, "computed"


if __name__ == "__main__":
    args = parse_arguments()

    try:
        # Extract parameters
        class_params, metadata = extract_parameters_from_bestfit(args.bestfit_file)

        # Display step 1 results
        print("\n" + "=" * 80)
        print("CLASS Parameters Extracted Successfully")
        print("=" * 80)
        print(f"\nBest-fit file:    {metadata['bestfit_file']}")
        print(f"YAML config file: {metadata['yaml_file']}")
        print(f"Parameters extracted: {metadata['parameters_extracted']}")

        if metadata["warnings"]:
            print("\nWarnings:")
            for warning in metadata["warnings"]:
                print(f"  ⚠ {warning}")

        print("\n" + "-" * 80)
        print("CLASS Input Parameters (ready for classy.set()):")
        print("-" * 80)

        # Sort and display parameters
        for key in sorted(class_params.keys()):
            value = class_params[key]
            if isinstance(value, float):
                print(f"  {key:30s} = {value:.15g}")
            elif isinstance(value, str):
                print(f"  {key:30s} = {value}")
            else:
                print(f"  {key:30s} = {value}")

        print("\n" + "=" * 80)
        print("Full dictionary for classy.set():")
        print("=" * 80)
        print(repr(class_params))

        # Step 2: Resolve model outputs and optional LCDM baseline outputs.
        print("\n" + "=" * 80)
        print("Running CLASS To Generate Background, P(k), and C_ℓ Evolution")
        print("=" * 80)
        run_info = resolve_or_run_class_outputs(
            class_params=class_params,
            bestfit_path=args.bestfit_file,
            output_dir=args.output_dir,
            reuse_only=args.reuse_background,
            # Preserve historical behavior unless an LCDM comparison run is requested.
            reuse_if_available=bool(args.lcdm_baseline),
        )
        output_root = Path(run_info["output_root"])

        if run_info["run_source"] == "reused":
            print("Model run skipped: reusing existing outputs.")
        else:
            print("Model run completed.")

        print(f"Output root:      {run_info['output_root']}")
        print(f"Background file:  {run_info['background_file']}")
        print(f"P(k) file:        {run_info['pk_file']}")
        print(f"C_ℓ file:         {run_info['cl_lensed_file']}")

        baseline_run_info: Optional[Dict[str, str]] = None
        baseline_background_dataset: Optional[Dict[str, Any]] = None
        baseline_pk_dataset: Optional[Dict[str, Any]] = None
        baseline_cl_dataset: Optional[Dict[str, Any]] = None

        if args.lcdm_baseline:
            print("\n" + "-" * 80)
            print("Resolving LCDM Baseline Outputs")
            print("-" * 80)

            lcdm_params, lcdm_metadata = extract_lcdm_baseline_parameters(
                args.lcdm_baseline
            )
            print(f"LCDM best-fit file: {lcdm_metadata['bestfit_file']}")
            print(f"LCDM YAML file:     {lcdm_metadata['yaml_file']}")
            print(f"LCDM params passed: {lcdm_metadata['parameters_extracted']}")

            baseline_run_info = resolve_or_run_class_outputs(
                class_params=lcdm_params,
                bestfit_path=args.lcdm_baseline,
                output_dir=args.output_dir,
                reuse_only=args.reuse_background,
                reuse_if_available=True,
            )

            if baseline_run_info["run_source"] == "reused":
                print("LCDM run skipped: reusing existing outputs.")
            else:
                print("LCDM run completed.")

            print(f"LCDM output root:   {baseline_run_info['output_root']}")
            print(f"LCDM background:    {baseline_run_info['background_file']}")
            print(f"LCDM P(k):          {baseline_run_info['pk_file']}")
            print(f"LCDM C_ℓ:           {baseline_run_info['cl_lensed_file']}")

        print("\nAll required CLASS outputs are ready. Now loading for plotting...")

        # Step 2.b: Load all three datasets and compute quantities for plotting.
        print("\n" + "=" * 80)
        print("Loading Background, P(k), and C_ℓ Data")
        print("=" * 80)

        bg_cache_file = str(
            Path(run_info["background_file"]).with_suffix(".processed.npz")
        )
        background_dataset, bg_source = load_or_compute_background_dataset(
            background_file=run_info["background_file"],
            cache_file=bg_cache_file,
        )
        print(f"\nBackground data:  source={bg_source}, cache={bg_cache_file}")
        print(f"  Rows:           {background_dataset['raw_table'].shape[0]}")
        print(
            f"  z-range:        [{np.nanmin(background_dataset['z']):.6g}, {np.nanmax(background_dataset['z']):.6g}]"
        )

        pk_cache_file = str(Path(run_info["pk_file"]).with_suffix(".processed.npz"))
        pk_dataset, pk_source = load_or_compute_pk_dataset(
            pk_file=run_info["pk_file"],
            cache_file=pk_cache_file,
        )
        print(f"\nP(k) data:        source={pk_source}, cache={pk_cache_file}")
        print(f"  k-points:       {pk_dataset['k'].shape[0]}")
        print(
            f"  k-range:        [{np.min(pk_dataset['k']):.6g}, {np.max(pk_dataset['k']):.6g}] h/Mpc"
        )

        cl_cache_file = str(
            Path(run_info["cl_lensed_file"]).with_suffix(".processed.npz")
        )
        cl_dataset, cl_source = load_or_compute_cl_dataset(
            cl_lensed_file=run_info["cl_lensed_file"],
            cache_file=cl_cache_file,
            lmax=9000,
        )
        print(f"\nC_ℓ data:         source={cl_source}, cache={cl_cache_file}")
        print(f"  ℓ-points:       {cl_dataset['ell'].shape[0]}")
        print(
            f"  ℓ-range:        [{np.min(cl_dataset['ell'])}, {np.max(cl_dataset['ell'])}]"
        )

        if baseline_run_info is not None:
            baseline_bg_cache_file = (
                f"{baseline_run_info['background_file']}.lcdm_omegas.processed.npz"
            )
            baseline_background_dataset, baseline_bg_source = (
                load_or_compute_lcdm_background_omegas_dataset(
                    background_file=baseline_run_info["background_file"],
                    cache_file=baseline_bg_cache_file,
                )
            )
            print(
                f"\nLCDM background Ω data: source={baseline_bg_source}, cache={baseline_bg_cache_file}"
            )
            print(
                f"  Rows:           {baseline_background_dataset['raw_table'].shape[0]}"
            )
            print(
                f"  z-range:        [{np.nanmin(baseline_background_dataset['z']):.6g}, {np.nanmax(baseline_background_dataset['z']):.6g}]"
            )

            baseline_pk_cache_file = str(
                Path(baseline_run_info["pk_file"]).with_suffix(".processed.npz")
            )
            baseline_pk_dataset, baseline_pk_source = load_or_compute_pk_dataset(
                pk_file=baseline_run_info["pk_file"],
                cache_file=baseline_pk_cache_file,
            )
            print(
                f"\nLCDM P(k) data:   source={baseline_pk_source}, cache={baseline_pk_cache_file}"
            )
            print(f"  k-points:       {baseline_pk_dataset['k'].shape[0]}")
            print(
                f"  k-range:        [{np.min(baseline_pk_dataset['k']):.6g}, {np.max(baseline_pk_dataset['k']):.6g}] h/Mpc"
            )

            baseline_cl_cache_file = str(
                Path(baseline_run_info["cl_lensed_file"]).with_suffix(".processed.npz")
            )
            baseline_cl_dataset, baseline_cl_source = load_or_compute_cl_dataset(
                cl_lensed_file=baseline_run_info["cl_lensed_file"],
                cache_file=baseline_cl_cache_file,
                lmax=9000,
            )
            print(
                f"\nLCDM C_ℓ data:    source={baseline_cl_source}, cache={baseline_cl_cache_file}"
            )
            print(f"  ℓ-points:       {baseline_cl_dataset['ell'].shape[0]}")
            print(
                f"  ℓ-range:        [{np.min(baseline_cl_dataset['ell'])}, {np.max(baseline_cl_dataset['ell'])}]"
            )

        # Pass runtime context to the plotting stage implemented at file bottom.
        globals()["_BESTFITPLOT_RUNTIME"] = {
            "background_dataset": background_dataset,
            "baseline_background_dataset": baseline_background_dataset,
            "pk_dataset": pk_dataset,
            "cl_dataset": cl_dataset,
            "baseline_pk_dataset": baseline_pk_dataset,
            "baseline_cl_dataset": baseline_cl_dataset,
            "output_root": str(output_root),
        }

        # Note about next steps
        print("\n" + "*" * 80)
        print("Next step: Build publication-quality plots")
        print("*" * 80)
        print("""
  5 plots are generated automatically:
  1. de Sitter conjecture parameters (s1, s2)
  2. Energy density evolution (Omega_scf, Omega_cdm)
  3. Swampland expression and equation of state (w)
  4. Matter power spectrum P(k)
  5. Lensed CMB angular power spectrum C_l (TT, EE, TE)

    If --lcdm_baseline is provided, plots 4 and 5 include ΛCDM reference curves.

  Use --reuse_background to skip rerunning CLASS while iterating on style.
        """)

    except FileNotFoundError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
    except ValueError as e:
        print(f"Validation Error: {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Unexpected Error: {e}", file=sys.stderr)
        import traceback

        traceback.print_exc()
        sys.exit(1)


# 3. Plot the results
_HIGH_CONTRAST_PALETTE: Dict[str, str] = {
    "black": "#000000",
    "blue": "#004488",
    "red": "#BB5566",
    "teal": "#009988",
    "yellow": "#DDAA33",
    "white": "#FFFFFF",
}

mpl.rcParams.update(
    {
        "font.family": "serif",  # Computer Modern — the default LaTeX font
        "font.size": 11.5,
        "axes.labelsize": 12,
        "xtick.labelsize": 11,
        "ytick.labelsize": 11,
        "legend.fontsize": 11,
        "lines.linewidth": 1.85,  # stronger curve visibility in print
        "axes.linewidth": 0.95,
        "xtick.direction": "in",  # inward ticks — journal standard
        "ytick.direction": "in",
        "xtick.minor.visible": True,  # show minor ticks
        "ytick.minor.visible": True,
        "xtick.major.size": 4.8,
        "ytick.major.size": 4.8,
        "xtick.minor.size": 2.4,
        "ytick.minor.size": 2.4,
        "xtick.major.width": 0.95,
        "ytick.major.width": 0.95,
        "xtick.minor.width": 0.72,
        "ytick.minor.width": 0.72,
        "lines.markersize": 4,  # smaller markers for print scale
        "errorbar.capsize": 3,  # visible end-caps (default is 0)
        "axes.xmargin": 0.02,  # hug the data (default is 0.05)
        "axes.ymargin": 0.02,
        "legend.frameon": False,  # no legend box
        "savefig.bbox": "tight",  # tight bounding box by default
        "savefig.dpi": 300,  # publication-quality resolution
        **(  # LaTeX if installed, else fallback
            {
                "text.usetex": True,  # real LaTeX for all text
                "pgf.preamble": (
                    r"\usepackage{fontspec}"
                    r"\usepackage{mathtools}"
                    r"\usepackage{amsfonts}"
                    r"\usepackage{amssymb}"
                    r"\usepackage[warnings-off={mathtools-overbracket,mathtools-colon}]{unicode-math}"
                    r"\setmainfont{IBM Plex Serif}"
                    r"\setsansfont{IBM Plex Sans}"
                    r"\setmonofont{IBM Plex Mono}"
                    r"\setmathfont{IBM Plex Math}"
                ),
                "text.latex.preamble": r"\usepackage{amsfonts}\usepackage{amssymb}",
                "pgf.texsystem": "lualatex",  # consistent PGF export
                "pgf.rcfonts": False,
            }  # let LaTeX control fonts
            if __import__("shutil").which("latex")
            else {
                "text.usetex": False,  # no TeX install found
                "mathtext.fontset": "cm",
            }  # Computer Modern via mathtext
        ),
    }
)


def _prepare_plot_arrays(background_dataset: Dict[str, Any]) -> Dict[str, np.ndarray]:
    """Prepare sorted plotting arrays and derived series used in all figures."""
    z = np.asarray(background_dataset["z"], dtype=float)
    order = np.argsort(z)

    z_plot = z[order]
    s1 = np.asarray(background_dataset["s1"], dtype=float)[order]
    # Convention: dataset stores minus_s2 = V''/V, so s2 = -V''/V = -minus_s2.
    s2 = -np.asarray(background_dataset["minus_s2"], dtype=float)[order]
    omega_scf = np.asarray(background_dataset["Omega_scf"], dtype=float)[order]
    omega_cdm = np.asarray(background_dataset["Omega_cdm"], dtype=float)[order]
    w = np.asarray(background_dataset["w"], dtype=float)[order]
    swampland_expr = np.asarray(background_dataset["swampland_expr"], dtype=float)[
        order
    ]

    return {
        "z": z_plot,
        "s1": s1,
        "s2": s2,
        "Omega_scf": omega_scf,
        "Omega_cdm": omega_cdm,
        "w": w,
        "swampland_expr": swampland_expr,
    }


def _prepare_lcdm_omega_arrays(dataset: Dict[str, Any]) -> Dict[str, np.ndarray]:
    """Prepare sorted LCDM Omega arrays for interpolation and plotting."""
    z = np.asarray(dataset["z"], dtype=float)
    order = np.argsort(z)

    return {
        "z": z[order],
        "Omega_cdm": np.asarray(dataset["Omega_cdm"], dtype=float)[order],
        "Omega_lambda": np.asarray(dataset["Omega_lambda"], dtype=float)[order],
    }


def _interp_series_on_z_grid(
    z_target: np.ndarray,
    z_source: np.ndarray,
    y_source: np.ndarray,
) -> np.ndarray:
    """Interpolate source series onto target z grid with NaN outside overlap."""
    mask = np.isfinite(z_source) & np.isfinite(y_source)
    if np.count_nonzero(mask) < 2:
        return np.full_like(z_target, np.nan, dtype=float)

    z_src = z_source[mask]
    y_src = y_source[mask]
    order = np.argsort(z_src)
    z_src = z_src[order]
    y_src = y_src[order]

    return np.interp(z_target, z_src, y_src, left=np.nan, right=np.nan)


def _style_redshift_axis(ax: Axes, z: np.ndarray) -> None:
    """Apply consistent redshift-axis styling with z=0 at the right side."""
    finite_z = z[np.isfinite(z)]
    zmax = float(np.nanmax(finite_z)) if finite_z.size else 1.0

    # Symlog preserves visibility near z=0 while handling the full cosmic range.
    ax.set_xscale("symlog", linthresh=1.0)
    ax.set_xlim(zmax, 0.0)

    # Publication-oriented tick design: explicit decade majors plus a terminal 0,
    # and sparse decade minors (2 and 5) for cleaner density.
    if zmax >= 1.0:
        max_pow = int(np.floor(np.log10(zmax)))
        major_ticks = [10.0**p for p in range(max_pow, -1, -1)] + [0.0]
    else:
        major_ticks = [zmax, 0.0]

    major_ticks = sorted(set(float(t) for t in major_ticks))

    major_labels = []
    for t in major_ticks:
        if np.isclose(t, 0.0):
            major_labels.append("0")
        elif t >= 1.0:
            p = int(np.round(np.log10(t)))
            major_labels.append(rf"$10^{{{p}}}$")
        else:
            major_labels.append("")
    ax.xaxis.set_major_locator(FixedLocator(major_ticks))
    ax.xaxis.set_major_formatter(FixedFormatter(major_labels))

    minor_ticks = []
    if zmax >= 10.0:
        for p in range(max_pow - 1, -1, -1):
            d = 10.0**p
            for m in (2, 5):
                t = m * d
                if 1.0 < t < zmax:
                    minor_ticks.append(t)

    # Keep a minimal set of linear-region minor ticks near z~0.
    minor_ticks.extend([0.2, 0.4, 0.6, 0.8])
    minor_ticks = sorted(set(minor_ticks))
    ax.xaxis.set_minor_locator(FixedLocator(minor_ticks))
    ax.xaxis.set_minor_formatter(NullFormatter())

    ax.set_xlabel(r"Redshift $z$")
    ax.grid(True, which="major", alpha=0.32, linewidth=0.6)
    ax.grid(True, which="minor", alpha=0.09, linewidth=0.4)


def _save_figure_bundle(fig: Figure, base_path: Path) -> None:
    """Save each figure as PNG/PDF/PGF for quick view and publication workflows."""
    fig.savefig(str(base_path.parent / f"{base_path.name}.png"))
    fig.savefig(str(base_path.parent / f"{base_path.name}.pdf"))
    fig.savefig(str(base_path.parent / f"{base_path.name}.pgf"))


def _apply_tight_ylims(
    ax: Axes,
    arrays: List[np.ndarray],
    pad_frac: float = 0.08,
) -> None:
    """Set robust y-limits with small padding for publication-ready hierarchy."""
    finite_chunks = [a[np.isfinite(a)] for a in arrays]
    finite_chunks = [a for a in finite_chunks if a.size > 0]
    if not finite_chunks:
        return

    y_all = np.concatenate(finite_chunks)
    y_lo = float(np.nanmin(y_all))
    y_hi = float(np.nanmax(y_all))

    if not np.isfinite(y_lo) or not np.isfinite(y_hi):
        return

    span = y_hi - y_lo
    if span <= 0.0:
        # Nearly constant curve: enforce a symmetric micro-window around value.
        center = y_lo
        eps = max(1e-6, abs(center) * 0.02)
        ax.set_ylim(center - eps, center + eps)
        return

    pad = span * pad_frac
    ax.set_ylim(y_lo - pad, y_hi + pad)


def make_three_plots(
    background_dataset: Dict[str, Any],
    output_root: str,
    baseline_background_dataset: Optional[Dict[str, Any]] = None,
) -> Dict[str, str]:
    """Create the three requested polished science plots and save them to disk."""
    series = _prepare_plot_arrays(background_dataset)
    z = series["z"]

    out_root = Path(output_root)
    out_dir = out_root.parent
    stem = out_root.name
    out_dir.mkdir(parents=True, exist_ok=True)

    c1 = _HIGH_CONTRAST_PALETTE["blue"]
    c2 = _HIGH_CONTRAST_PALETTE["teal"]
    c3 = _HIGH_CONTRAST_PALETTE["red"]
    c4 = _HIGH_CONTRAST_PALETTE["black"]

    ls_primary = "-"
    ls_secondary = "--"

    legend_kw = {
        "loc": "lower left",
        "bbox_to_anchor": (0.02, 0.06),
        "handlelength": 2.2,
        "labelspacing": 0.35,
        "borderaxespad": 0.0,
    }

    # Plot 1: de Sitter conjecture parameters s1 and s2.
    fig1, ax1 = plt.subplots(figsize=(6.4, 4.1))
    ax1.plot(
        z,
        series["s1"],
        color=c1,
        linestyle=ls_primary,
        label=r"$\mathfrak{s}_1 = |V_{\phi}|/V$",
    )
    ax1.plot(
        z,
        series["s2"],
        color=c2,
        linestyle=ls_secondary,
        label=r"$\mathfrak{s}_2 = -V_{\phi\phi}/V$",
    )
    _style_redshift_axis(ax1, z)
    _apply_tight_ylims(ax1, [series["s1"], series["s2"]], pad_frac=0.04)
    ax1.set_ylabel(r"de Sitter Parameters")
    ax1.legend(**legend_kw)
    fig1.tight_layout()
    p1 = out_dir / f"{stem}_plot1_ds"
    _save_figure_bundle(fig1, p1)
    plt.close(fig1)

    # Plot 2: Omega_scf and Omega_cdm (+ Delta panel against LCDM when available).
    if baseline_background_dataset is None:
        fig2, ax2 = plt.subplots(figsize=(6.4, 4.1))
        ax2.plot(
            z,
            series["Omega_scf"],
            color=c3,
            linestyle=ls_primary,
            label=r"$\Omega_{\phi}$",
        )
        ax2.plot(
            z,
            series["Omega_cdm"],
            color=c4,
            linestyle=ls_secondary,
            label=r"$\Omega_{\mathrm{cdm}}$",
        )
        _style_redshift_axis(ax2, z)
        _apply_tight_ylims(
            ax2, [series["Omega_scf"], series["Omega_cdm"]], pad_frac=0.035
        )
        ax2.set_ylabel(r"Relative Energy Density")
        ax2.legend(**legend_kw)
    else:
        fig2, (ax2_top, ax2_bottom) = plt.subplots(
            2,
            1,
            sharex=True,
            figsize=(6.4, 5.7),
            gridspec_kw={"height_ratios": [3.0, 2.1], "hspace": 0.02},
        )

        # Upper panel kept as the current Omega plot (model only).
        ax2_top.plot(
            z,
            series["Omega_scf"],
            color=c3,
            linestyle=ls_primary,
            label=r"$\Omega_{\phi}$",
        )
        ax2_top.plot(
            z,
            series["Omega_cdm"],
            color=c4,
            linestyle=ls_secondary,
            label=r"$\Omega_{\mathrm{cdm}}$",
        )
        _style_redshift_axis(ax2_top, z)
        _apply_tight_ylims(
            ax2_top, [series["Omega_scf"], series["Omega_cdm"]], pad_frac=0.035
        )
        # Ensure upper y-limit is at least 1.0 for flat-universe context
        ylim_bottom, ylim_top = ax2_top.get_ylim()
        ax2_top.set_ylim(ylim_bottom, max(ylim_top, 1.0))
        ax2_top.set_ylabel(r"Relative Energy Density")
        ax2_top.legend(**legend_kw)

        # Configure shared redshift axis for ganged plots (like matplotlib gallery example):
        # Top panel: show bottom spine and ticks (appears in middle between panels)
        ax2_top.spines["bottom"].set_visible(True)
        ax2_top.tick_params(axis="x", which="both", bottom=True, labelbottom=False)

        # Bottom panel: hide top spine, show bottom spine and ticks with labels
        ax2_bottom.spines["top"].set_visible(False)
        ax2_bottom.spines["bottom"].set_visible(True)
        ax2_bottom.tick_params(axis="x", which="both", bottom=True, labelbottom=True)

        # Put the axis label only at the very bottom
        ax2_top.set_xlabel("")
        ax2_bottom.xaxis.set_label_position("bottom")
        ax2_bottom.set_xlabel(r"Redshift $z$")

        # Lower panel: Delta Omega evolutions.
        baseline_series = _prepare_lcdm_omega_arrays(baseline_background_dataset)
        omega_cdm_lcdm_on_model = _interp_series_on_z_grid(
            z_target=series["z"],
            z_source=baseline_series["z"],
            y_source=baseline_series["Omega_cdm"],
        )
        omega_lambda_lcdm_on_model = _interp_series_on_z_grid(
            z_target=series["z"],
            z_source=baseline_series["z"],
            y_source=baseline_series["Omega_lambda"],
        )

        delta_omega_cdm = series["Omega_cdm"] - omega_cdm_lcdm_on_model
        delta_omega_de = series["Omega_scf"] - omega_lambda_lcdm_on_model

        ax2_bottom.plot(
            z,
            delta_omega_cdm,
            color=c4,
            linestyle=ls_primary,
            label=r"$\Delta\Omega_{\mathrm{cdm}}=\Omega_{\mathrm{cdm}}^{\mathrm{model}}-\Omega_{\mathrm{cdm}}^{\Lambda\mathrm{CDM}}$",
        )
        ax2_bottom.plot(
            z,
            delta_omega_de,
            color=c3,
            linestyle=ls_secondary,
            label=r"$\Delta\Omega_{\mathrm{DE}}=\Omega_{\phi}-\Omega_{\Lambda}$",
        )
        ax2_bottom.axhline(
            0.0,
            color="0.20",
            linestyle=(0, (5, 2.5)),
            linewidth=1.0,
            alpha=0.9,
            zorder=1,
        )
        _apply_tight_ylims(ax2_bottom, [delta_omega_cdm, delta_omega_de], pad_frac=0.08)
        ax2_bottom.set_ylabel(r"$\Delta\Omega$")
        ax2_bottom.grid(True, which="major", alpha=0.32, linewidth=0.6)
        ax2_bottom.grid(True, which="minor", alpha=0.09, linewidth=0.4)
        ax2_bottom.legend(
            loc="lower left",
            bbox_to_anchor=(0.02, 0.04),
            handlelength=2.2,
            labelspacing=0.25,
            borderaxespad=0.0,
            fontsize=9.6,
        )
    fig2.tight_layout()
    p2 = out_dir / f"{stem}_plot2_omegas"
    _save_figure_bundle(fig2, p2)
    plt.close(fig2)

    # Plot 3: swampland expression and w, plus horizontal y=0 and y=-1 references.
    fig3, ax3 = plt.subplots(figsize=(6.4, 4.1))
    ax3.plot(
        z,
        series["swampland_expr"],
        color=c2,
        linestyle=ls_secondary,
        label=r"$1+w-0.15\,\mathfrak{s}_1^2$",
    )
    ax3.plot(z, series["w"], color=c1, linestyle=ls_primary, label=r"$w$")
    ax3.axhline(
        0.0, color="0.20", linestyle=(0, (5, 2.5)), linewidth=1.0, alpha=0.9, zorder=1
    )
    ax3.axhline(
        -1.0,
        color="0.35",
        linestyle=(0, (1.2, 2.0)),
        linewidth=1.0,
        alpha=0.85,
        zorder=1,
    )
    _style_redshift_axis(ax3, z)
    _apply_tight_ylims(ax3, [series["swampland_expr"], series["w"]], pad_frac=0.05)
    ax3.set_ylabel(r"Equation of State")
    ax3.legend(**legend_kw)
    fig3.tight_layout()
    p3 = out_dir / f"{stem}_plot3_swampland_w"
    _save_figure_bundle(fig3, p3)
    plt.close(fig3)

    return {
        "plot1_png": str(p1.parent / f"{p1.name}.png"),
        "plot1_pdf": str(p1.parent / f"{p1.name}.pdf"),
        "plot1_pgf": str(p1.parent / f"{p1.name}.pgf"),
        "plot2_png": str(p2.parent / f"{p2.name}.png"),
        "plot2_pdf": str(p2.parent / f"{p2.name}.pdf"),
        "plot2_pgf": str(p2.parent / f"{p2.name}.pgf"),
        "plot3_png": str(p3.parent / f"{p3.name}.png"),
        "plot3_pdf": str(p3.parent / f"{p3.name}.pdf"),
        "plot3_pgf": str(p3.parent / f"{p3.name}.pgf"),
    }


def make_pk_plot(
    pk_dataset: Dict[str, Any],
    output_root: str,
    baseline_pk_dataset: Optional[Dict[str, Any]] = None,
) -> Dict[str, str]:
    """Create a publication-quality P(k) plot and save to disk.

    Plots matter power spectrum P(k) vs k in log-log scale.
    """
    k = np.asarray(pk_dataset["k"], dtype=float)
    P_k = np.asarray(pk_dataset["P_k"], dtype=float)

    out_root = Path(output_root)
    out_dir = out_root.parent
    stem = out_root.name

    c_pk = _HIGH_CONTRAST_PALETTE["blue"]
    c_pk_ref = _HIGH_CONTRAST_PALETTE["black"]

    fig, ax = plt.subplots(figsize=(6.4, 4.1))
    ax.loglog(k, P_k, color=c_pk, linewidth=1.85, label=r"$P(k)$ model")

    if baseline_pk_dataset is not None:
        k_ref = np.asarray(baseline_pk_dataset["k"], dtype=float)
        P_k_ref = np.asarray(baseline_pk_dataset["P_k"], dtype=float)
        ax.loglog(
            k_ref,
            P_k_ref,
            color=c_pk_ref,
            linewidth=1.4,
            linestyle=(0, (4.0, 2.1)),
            label=r"$P(k)$ $\Lambda$CDM",
        )

    ax.set_xlabel(r"Wavenumber $k$ [$h/\mathrm{Mpc}$]")
    ax.set_ylabel(r"Matter Power Spectrum $P(k)$ [$(Mpc/h)^3$]")
    ax.grid(True, which="major", alpha=0.32, linewidth=0.6)
    ax.grid(True, which="minor", alpha=0.09, linewidth=0.4)
    ax.legend(loc="lower left", handlelength=2.2, labelspacing=0.35, borderaxespad=0.0)

    fig.tight_layout()
    p_pk = out_dir / f"{stem}_plot4_pk"
    _save_figure_bundle(fig, p_pk)
    plt.close(fig)

    return {
        "plot4_png": str(p_pk.parent / f"{p_pk.name}.png"),
        "plot4_pdf": str(p_pk.parent / f"{p_pk.name}.pdf"),
        "plot4_pgf": str(p_pk.parent / f"{p_pk.name}.pgf"),
    }


def make_cl_plot(
    cl_dataset: Dict[str, Any],
    output_root: str,
    baseline_cl_dataset: Optional[Dict[str, Any]] = None,
) -> Dict[str, str]:
    """Create a publication-quality C_ℓ plot and save to disk.

    Plots scaled lensed C_ℓ (TT, EE, TE) vs ℓ in log-log scale.
    """
    ell = np.asarray(cl_dataset["ell"], dtype=float)
    Cl_TT = np.asarray(cl_dataset["Cl_TT_scaled"], dtype=float)
    Cl_EE = np.asarray(cl_dataset["Cl_EE_scaled"], dtype=float)
    Cl_TE = np.asarray(cl_dataset["Cl_TE_scaled"], dtype=float)

    out_root = Path(output_root)
    out_dir = out_root.parent
    stem = out_root.name

    c_tt = _HIGH_CONTRAST_PALETTE["blue"]
    c_ee = _HIGH_CONTRAST_PALETTE["red"]
    c_te = _HIGH_CONTRAST_PALETTE["teal"]

    ls_primary = "-"

    fig, ax = plt.subplots(figsize=(6.4, 4.1))
    ax.loglog(
        ell, Cl_TT, color=c_tt, linestyle=ls_primary, linewidth=1.85, label=r"$T T$"
    )
    ax.loglog(
        ell, Cl_EE, color=c_ee, linestyle=ls_primary, linewidth=1.85, label=r"$E E$"
    )
    ax.loglog(
        ell, Cl_TE, color=c_te, linestyle=ls_primary, linewidth=1.85, label=r"$T E$"
    )

    if baseline_cl_dataset is not None:
        ell_ref = np.asarray(baseline_cl_dataset["ell"], dtype=float)
        cl_tt_ref = np.asarray(baseline_cl_dataset["Cl_TT_scaled"], dtype=float)
        cl_ee_ref = np.asarray(baseline_cl_dataset["Cl_EE_scaled"], dtype=float)
        cl_te_ref = np.asarray(baseline_cl_dataset["Cl_TE_scaled"], dtype=float)

        ref_ls = (0, (4.0, 2.1))
        ax.loglog(
            ell_ref,
            cl_tt_ref,
            color=c_tt,
            linestyle=ref_ls,
            linewidth=1.25,
            alpha=0.82,
            label=r"$T T$ $\Lambda$CDM",
        )
        ax.loglog(
            ell_ref,
            cl_ee_ref,
            color=c_ee,
            linestyle=ref_ls,
            linewidth=1.25,
            alpha=0.82,
            label=r"$E E$ $\Lambda$CDM",
        )
        ax.loglog(
            ell_ref,
            cl_te_ref,
            color=c_te,
            linestyle=ref_ls,
            linewidth=1.25,
            alpha=0.82,
            label=r"$T E$ $\Lambda$CDM",
        )

    ax.set_xlabel(r"Multipole Moment $\ell$")
    ax.set_ylabel(r"$\ell(\ell+1)/(2\pi)\, C_\ell$ [$\mu K^2$]")
    ax.grid(True, which="major", alpha=0.32, linewidth=0.6)
    ax.grid(True, which="minor", alpha=0.09, linewidth=0.4)
    ax.legend(loc="lower left", handlelength=2.2, labelspacing=0.35, borderaxespad=0.0)

    fig.tight_layout()
    p_cl = out_dir / f"{stem}_plot5_cl_lensed"
    _save_figure_bundle(fig, p_cl)
    plt.close(fig)

    return {
        "plot5_png": str(p_cl.parent / f"{p_cl.name}.png"),
        "plot5_pdf": str(p_cl.parent / f"{p_cl.name}.pdf"),
        "plot5_pgf": str(p_cl.parent / f"{p_cl.name}.pgf"),
    }


if __name__ == "__main__" and "_BESTFITPLOT_RUNTIME" in globals():
    _runtime = globals()["_BESTFITPLOT_RUNTIME"]

    print("\n" + "=" * 80)
    print("Rendering All Plots")
    print("=" * 80)

    _plot_paths = {}

    # Plot 1-3: Background evolution plots
    print("\n  Rendering background plots (de Sitter, energy densities, swampland)...")
    _plot_paths.update(
        make_three_plots(
            background_dataset=_runtime["background_dataset"],
            output_root=_runtime["output_root"],
            baseline_background_dataset=_runtime.get("baseline_background_dataset"),
        )
    )

    # Plot 4: P(k) plot
    print("  Rendering P(k) plot...")
    _plot_paths.update(
        make_pk_plot(
            pk_dataset=_runtime["pk_dataset"],
            output_root=_runtime["output_root"],
            baseline_pk_dataset=_runtime.get("baseline_pk_dataset"),
        )
    )

    # Plot 5: C_ℓ plot
    print("  Rendering C_ℓ plot (TT, EE, TE)...")
    _plot_paths.update(
        make_cl_plot(
            cl_dataset=_runtime["cl_dataset"],
            output_root=_runtime["output_root"],
            baseline_cl_dataset=_runtime.get("baseline_cl_dataset"),
        )
    )

    print("\n" + "=" * 80)
    print("All Plots Generated Successfully")
    print("=" * 80)
    for _name in sorted(_plot_paths.keys()):
        _path = _plot_paths[_name]
        print(f"{_name:12s}: {_path}")
