# This script
# First, extract the model parameters from the passed *.bestfit file
# Second, runs CLASS with those parameters to obtain:
#   - The scalar field evolution
#   - The scalar field potential evolution including the first and second derivatives
#   - The equation of state evolution of the scalar field
#   - The dark matter and dark energy density evolution
# Third, plots
#   - the de Sitter conjecture |dV|/V, |d^2V|/V, and the equation of state w as a function of redshift z
#   - the dark matter and dark energy density evolution as a function of redshift z
#   - the EoS evolution as a function of redshift z to check for phantom crossing
#   - 1+w-0.15s_1^2 as a function of redshift z to check for the swampland conjecture

# Usage:
# python BestFitPlot.py --bestfit_file path/to/bestfit_file.bestfit --output_dir path/to/output_dir
# The bestfit_file should be a .bestfit file generated by the MCMC analysis, containing the best-fit parameters for the model.
# The output_dir is the directory where the plots will be saved.
# Default ouput dir is the current directory.
# --reuse_background can be used to skip rerunning CLASS and reuse existing background data and cache files, e.g. to just regenerate the plots.

# 1. Extract the model parameters from the passed *.bestfit file

"""
BestFitPlot.py: Extract best-fit parameters from MCMC chains and prepare them for CLASS.

This script:
1. Extracts model parameters from a *.bestfit file (Cobaya output format)
2. Loads the corresponding *.input.yaml file (Cobaya MCMC configuration)
3. Maps Cobaya/MCMC parameter names to CLASS parameter names
4. Combines special parameters (e.g., scalar field parameters) into CLASS-compatible strings
5. Returns a dictionary ready to pass to classy.set()

The resulting CLASS parameters can then be used to:
- Run CLASS with those parameters to obtain scalar field evolution
- Compute scalar field potential and equation of state evolution
- Extract dark matter and energy density evolution
- Generate cosmological plots for analysis

Usage:
    python BestFitPlot.py --bestfit_file path/to/bestfit_file.bestfit [--output_dir path/to/output_dir]

    The bestfit_file should be a .bestfit file generated by the MCMC analysis.
    The output_dir is where the results will be saved (default: current directory).
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path
from typing import Dict, Any, Tuple, List, Optional
import numpy as np
import yaml
import re


def parse_arguments() -> argparse.Namespace:
    """Parse command-line arguments for BestFitPlot.

    Returns:
        argparse.Namespace: Parsed arguments with 'bestfit_file' and 'output_dir'
    """
    parser = argparse.ArgumentParser(
        description="Extract CLASS parameters from Cobaya MCMC best-fit files"
    )
    parser.add_argument(
        "--bestfit_file",
        type=str,
        required=True,
        help="Path to the .bestfit file (Cobaya MCMC output)",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default=".",
        help="Output directory for results (default: current directory)",
    )
    parser.add_argument(
        "--reuse_background",
        action="store_true",
        help=(
            "Reuse existing <output_root>_background.dat and cache instead of rerunning CLASS. "
            "Useful while iterating on plotting aesthetics."
        ),
    )
    return parser.parse_args()


def load_bestfit_file(bestfit_path: str) -> Dict[str, float]:
    """Parse a Cobaya .bestfit file and extract parameter values.

    The .bestfit file format contains lines with:
        index  value  parameter_name  LaTeX_description

    Parameters starting with '#' are ignored (comment lines).

    Args:
        bestfit_path: Path to the .bestfit file

    Returns:
        Dictionary mapping parameter names to their float values

    Raises:
        FileNotFoundError: If the file does not exist
        ValueError: If the file format is invalid
    """
    if not os.path.exists(bestfit_path):
        raise FileNotFoundError(f"Best-fit file not found: {bestfit_path}")

    parameters = {}
    with open(bestfit_path, "r") as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()

            # Skip empty lines and comments
            if not line or line.startswith("#") or line.startswith("-"):
                continue

            # Parse the line: index  value  parameter_name  LaTeX_description
            parts = line.split()
            if len(parts) < 3:
                continue

            try:
                # Extract index, value, and parameter name
                index = int(parts[0])
                value = float(parts[1])
                param_name = parts[2]

                # Store the parameter
                parameters[param_name] = value
            except (ValueError, IndexError):
                # Skip lines that don't match the expected format
                continue

    if not parameters:
        raise ValueError(f"No parameters found in file: {bestfit_path}")

    return parameters


def load_input_yaml(yaml_path: str) -> Dict[str, Any]:
    """Load a Cobaya .input.yaml file (MCMC configuration).

    Args:
        yaml_path: Path to the .input.yaml file

    Returns:
        Parsed YAML dictionary

    Raises:
        FileNotFoundError: If the file does not exist
        yaml.YAMLError: If the YAML is invalid
    """
    if not os.path.exists(yaml_path):
        raise FileNotFoundError(f"Input YAML file not found: {yaml_path}")

    with open(yaml_path, "r") as f:
        config = yaml.safe_load(f)

    return config


def find_input_yaml(bestfit_path: str) -> str:
    """Find the corresponding .input.yaml file for a .bestfit file.

    Assumes the .input.yaml file has the same name as .bestfit but with
    ".input.yaml" extension instead of ".bestfit".

    Args:
        bestfit_path: Path to the .bestfit file

    Returns:
        Path to the corresponding .input.yaml file

    Raises:
        FileNotFoundError: If the .input.yaml file is not found
    """
    base_path = bestfit_path.rsplit(".bestfit", 1)[0]
    yaml_path = f"{base_path}.input.yaml"

    if not os.path.exists(yaml_path):
        raise FileNotFoundError(
            f"Could not find corresponding YAML file: {yaml_path}\n"
            f"Expected base name: {base_path}"
        )

    return yaml_path


# List of all known CLASS input parameters
# This is used to filter out derived and output parameters from YAML specifications
_CLASS_INPUT_PARAMETERS = {
    # Cosmological parameters - standard
    "H0",
    "h",
    "theta_s_100",
    "omega_b",
    "Omega_b",
    "omega_cdm",
    "Omega_cdm",
    "Omega_k",
    "Omega_Lambda",
    "Omega_fld",
    "Omega_scf",
    "T_cmb",
    "YHe",
    "recombination",
    # Primordial perturbations
    "n_s",
    "alpha_s",
    "A_s",
    "k_pivot",
    # Reionization
    "z_reio",
    "tau_reio",
    "reio_parametrization",
    "reionization_exponent",
    "reionization_width",
    "helium_fullreio_redshift",
    "helium_fullreio_width",
    # Neutrino/relativistic species
    "N_ur",
    "N_ncdm",
    "m_ncdm",
    "omega_ncdm",
    "Omega_ncdm",
    "deg_ncdm",
    "sBBN file",
    # Dark energy - fluid
    "w0_fld",
    "wa_fld",
    "cs2_fld",
    "fluid_equation_of_state",
    "Omega_EDE",
    # Scalar field dark energy
    "scf_potential",
    "scf_parameters",
    "scf_tuning_index",
    "attractor_ic_scf",
    # Interacting dark matter (custom extension)
    "model_cdm",
    "cdm_c",
    # Output options
    "output",
    "modes",
    "ic",
    "gauge",
    "non_linear",
    "l_max_scalars",
    "l_max_tensors",
    "l_max_lss",
    "P_k_max_h/Mpc",
    "P_k_max_1/Mpc",
    "k_output_values",
    "z_pk",
    "number_count_contributions",
    "selection",
    "selection_mean",
    "selection_width",
    "tensor_method",
    "perturbations_verbose",
    "background_verbose",
    "input_verbose",
    "thermodynamics_verbose",
    "lensing_verbose",
    "transfer_verbose",
    "primordial_verbose",
    "harmonic_verbose",
    "fourier_verbose",
    "output_verbose",
    # Energy injection
    "DM_annihilation_cross_section",
    "DM_annihilation_mass",
    "DM_decay_fraction",
    "DM_decay_Gamma",
    # Precision/computation options
    "compute_damping_scale",
    "varying_fundamental_constants",
}

# Parameters that can appear in chains as derived/reporting outputs but are not
# valid CLASS input keys.
_NON_INPUT_PARAMETERS = {
    "cdm_f_phi0",
}


def extract_class_parameters(
    bestfit_values: Dict[str, float], yaml_config: Dict[str, Any]
) -> Dict[str, Any]:
    """Map Cobaya MCMC parameters to CLASS input parameters.

    This function:
    1. Extracts parameters marked as drop: false and derived: false (or no 'derived' key)
    2. Handles special scalar field parameters that need to be combined into 'scf_parameters'
    3. Includes extra_args from the YAML theory.classy section
    4. Filters to only include known CLASS input parameters

    Args:
        bestfit_values: Parameter values extracted from .bestfit file
        yaml_config: Parsed YAML configuration from .input.yaml

    Returns:
        Dictionary ready to pass to classy.set(), with CLASS parameter names and values

    Raises:
        KeyError: If required sections are missing from the YAML
        ValueError: If parameter extraction fails
    """
    class_params = {}

    # 1. Extract theory.classy.extra_args (these are trusted CLASS inputs)
    if "theory" in yaml_config and "classy" in yaml_config["theory"]:
        classy_config = yaml_config["theory"]["classy"]
        if "extra_args" in classy_config:
            class_params.update(classy_config["extra_args"])

    # 2. Extract primary (non-dropped, non-derived) parameters from params section
    if "params" not in yaml_config:
        raise KeyError("'params' section not found in YAML configuration")

    params_config = yaml_config["params"]
    dropped_scf_params = {}  # Store dropped scalar field parameters for recombination

    for param_name, param_spec in params_config.items():
        if param_name in _NON_INPUT_PARAMETERS:
            continue

        # Skip output/tracking parameters that are not CLASS inputs
        if param_name not in _CLASS_INPUT_PARAMETERS and not param_name.startswith(
            "scf_"
        ):
            continue

        # Skip if parameter specification is a scalar value (like Omega_fld = 0.0)
        if not isinstance(param_spec, dict):
            # Handle direct scalar assignments (e.g., Omega_fld: 0.0)
            if param_name in _CLASS_INPUT_PARAMETERS:
                class_params[param_name] = param_spec
            continue

        # Determine if this parameter should be included in CLASS input
        is_dropped = param_spec.get("drop", False)
        has_derived = "derived" in param_spec

        # Special handling for scf_parameters: it should be constructed, not directly copied
        if param_name == "scf_parameters":
            # This will be handled separately after collecting all needed parameters
            continue

        # Extract parameter value from bestfit if it exists
        if param_name in bestfit_values:
            value = bestfit_values[param_name]

            # Collect dropped scalar field parameters for later recombination
            if is_dropped and param_name.startswith("scf_"):
                dropped_scf_params[param_name] = value

            # Include parameter if:
            # 1. It's not dropped and not derived, OR
            # 2. It's a dropped scalar field parameter (for later reconstruction)
            if not is_dropped and not has_derived:
                class_params[param_name] = value
            elif is_dropped and param_name.startswith("scf_"):
                # Keep dropped scalar field params for reconstruction
                dropped_scf_params[param_name] = value
        elif not is_dropped and not has_derived and param_name in params_config:
            # If parameter spec has a 'value' field, use it
            if isinstance(param_spec, dict) and "value" in param_spec:
                class_params[param_name] = param_spec["value"]

    # 3. Reconstruct scf_parameters from individual components
    if dropped_scf_params and "chi_ini" in bestfit_values:
        class_params["scf_parameters"] = _construct_scf_parameters(
            dropped_scf_params=dropped_scf_params,
            bestfit_values=bestfit_values,
            yaml_config=yaml_config,
        )

    # 4. CLASS expects yes/no strings for boolean-like flags.
    for key, value in list(class_params.items()):
        if isinstance(value, bool):
            class_params[key] = "yes" if value else "no"

    return class_params


def _construct_scf_parameters(
    dropped_scf_params: Dict[str, float],
    bestfit_values: Dict[str, float],
    yaml_config: Dict[str, Any],
) -> str:
    """Construct the scf_parameters string from individual scalar field parameters.

    The scf_parameters string is a comma-separated list of CLASS scalar field parameters
    in the order: c1, c2, c3, c4, q1, q2, q3, q4, exp1, exp2, phi_ini, phi_prime_ini

    All values are taken directly from the .bestfit file, which contains the actual
    best-fit values computed by Cobaya. Even parameters marked as 'derived' in the
    YAML have their computed values in the bestfit file.

    Args:
        dropped_scf_params: Individual scalar field parameters from .bestfit
        bestfit_values: All parameter values from .bestfit
        yaml_config: YAML configuration for extracting default values if needed

    Returns:
        A comma-separated string of scalar field parameters for CLASS
    """
    # Define the expected order of parameters in scf_parameters
    scf_param_order = [
        "scf_c1",
        "scf_c2",
        "scf_c3",
        "scf_c4",
        "scf_q1",
        "scf_q2",
        "scf_q3",
        "scf_q4",
        "scf_exp1",
        "scf_exp2",
        "scf_phi_ini",
        "scf_phi_prime_ini",
    ]

    scf_values = []

    for scf_param in scf_param_order:
        # Try to get the value from dropped_scf_params (all scf params are dropped in YAML)
        if scf_param in dropped_scf_params:
            scf_values.append(str(dropped_scf_params[scf_param]))
        else:
            # Use default values from YAML if available
            if (
                "params" in yaml_config
                and scf_param in yaml_config["params"]
                and isinstance(yaml_config["params"][scf_param], dict)
                and "value" in yaml_config["params"][scf_param]
            ):
                scf_values.append(str(yaml_config["params"][scf_param]["value"]))
            else:
                # Default fallback (typically 0.0 for most scalar field parameters)
                scf_values.append("0.0")

    return ",".join(scf_values)


def extract_parameters_from_bestfit(
    bestfit_path: str, yaml_path: Optional[str] = None
) -> Tuple[Dict[str, Any], Dict[str, Any]]:
    """Main function: Extract CLASS parameters from Cobaya best-fit and YAML files.

    This is the primary entry point that orchestrates the entire parameter extraction process.

    Args:
        bestfit_path: Path to the .bestfit file
        yaml_path: Path to the .input.yaml file (auto-detected if None)

    Returns:
        Tuple containing:
            - Dictionary of CLASS parameters ready for classy.set()
            - Dictionary of extraction metadata and warnings

    Raises:
        FileNotFoundError: If required files are not found
        ValueError: If extraction fails

    Example:
        >>> class_params, metadata = extract_parameters_from_bestfit(
        ...     'hyperbolic_Planck_InitCond_MCMC.bestfit'
        ... )
        >>> print(class_params)
        {'H0': 67.32, 'n_s': 0.964, ..., 'scf_parameters': '1.037e-07,0.5,0.0,...'}
    """
    # Find YAML file if not provided
    if yaml_path is None:
        yaml_path = find_input_yaml(bestfit_path)

    # Load files
    bestfit_values = load_bestfit_file(bestfit_path)
    yaml_config = load_input_yaml(yaml_path)

    # Extract CLASS parameters
    class_params = extract_class_parameters(bestfit_values, yaml_config)

    # Prepare metadata
    metadata = {
        "bestfit_file": os.path.abspath(bestfit_path),
        "yaml_file": os.path.abspath(yaml_path),
        "parameters_extracted": len(class_params),
        "warnings": [],
    }

    return class_params, metadata


def _serialize_class_value(value: Any) -> str:
    """Serialize a Python value into a CLASS .ini-compatible value string."""
    if isinstance(value, bool):
        return "yes" if value else "no"
    if value is None:
        return ""
    return str(value)


# 2.a) Run CLASS with the extracted parameters to obtain the background data.


def run_class_background(
    class_params: Dict[str, Any],
    bestfit_path: str,
    output_dir: str,
) -> Dict[str, str]:
    """Run CLASS with extracted parameters and write a background output file.

    This function creates an auto-generated CLASS .ini file, forces
    `write_background = yes`, runs CLASS, and returns paths to generated files.

    Args:
        class_params: Dictionary of CLASS parameters from step 1.
        bestfit_path: Path to source best-fit file, used to derive output names.
        output_dir: Directory where generated .ini and CLASS outputs are written.

    Returns:
        Dict containing:
            - class_executable
            - generated_ini
            - background_file
            - output_root

    Raises:
        FileNotFoundError: If CLASS executable is missing.
        RuntimeError: If CLASS execution fails.
    """
    repo_root = Path(__file__).resolve().parents[1]
    class_executable = repo_root / "class"

    if not class_executable.exists():
        raise FileNotFoundError(
            f"CLASS executable not found at: {class_executable}. Build it with 'make class -j'."
        )

    out_dir = Path(output_dir).expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    run_label = Path(bestfit_path).name.replace(".bestfit", "")
    output_root = out_dir / run_label
    ini_path = out_dir / f"{run_label}_autogen.ini"

    # Force background output and deterministic overwrite behavior.
    run_params = dict(class_params)
    run_params["write_background"] = "yes"
    run_params["overwrite_root"] = "yes"
    run_params["root"] = str(output_root)
    # For a background-only extraction run, disable non-linear modules to avoid
    # requiring perturbation outputs (e.g. mPk/tCl) in this development step.
    run_params["non linear"] = ""

    # Normalize sBBN file path when only a bare filename is provided in YAML.
    # CLASS concatenates base_path + sBBN file, so we need a relative subpath.
    sbbn_key = "sBBN file"
    if sbbn_key in run_params:
        sbbn_value = str(run_params[sbbn_key]).strip()
        if sbbn_value and "/" not in sbbn_value and "\\" not in sbbn_value:
            run_params[sbbn_key] = f"/external/bbn/{sbbn_value}"
        elif sbbn_value.startswith("bbn/"):
            run_params[sbbn_key] = f"/external/{sbbn_value}"

    with open(ini_path, "w") as f:
        f.write("# Auto-generated by BestFitPlot.py\n")
        f.write(f"# Source bestfit: {bestfit_path}\n\n")
        for key in sorted(run_params.keys()):
            f.write(f"{key} = {_serialize_class_value(run_params[key])}\n")

    run_result = subprocess.run(
        [str(class_executable), str(ini_path)],
        cwd=str(repo_root),
        capture_output=True,
        text=True,
    )

    background_file = Path(f"{output_root}_background.dat")

    if run_result.returncode != 0:
        stdout_tail = "\n".join(run_result.stdout.splitlines()[-30:])
        stderr_tail = "\n".join(run_result.stderr.splitlines()[-30:])
        raise RuntimeError(
            "CLASS run failed.\n"
            f"Return code: {run_result.returncode}\n"
            f"Generated ini: {ini_path}\n"
            f"--- STDOUT (tail) ---\n{stdout_tail}\n"
            f"--- STDERR (tail) ---\n{stderr_tail}"
        )

    if not background_file.exists():
        raise RuntimeError(
            "CLASS run completed but background file was not found.\n"
            f"Expected: {background_file}\n"
            f"Generated ini: {ini_path}"
        )

    return {
        "class_executable": str(class_executable),
        "generated_ini": str(ini_path),
        "background_file": str(background_file),
        "output_root": str(output_root),
    }


# 2.b) Extract the background data from the stored file and compute quantities
#      Obtain the scalar field evolution, the scalar field potential evolution including the first and second derivatives,
#      the equation of state evolution of the scalar field, and the dark matter and dark energy density evolution from CLASS
#      We extract
#      - the redhisft z
#      - the dark matter density rho_cdm
#      - the dark energy density rho_scf
#      - the critical density rho_crit
#      - the scalar field pressur p_scf
#      - the scalar field potential V
#      - the scalar field potential first derivative dV
#      - the scalar field potential second derivative d2V
#      Based on these quantities, we then compute
#      - the equation of state w = p_scf / rho_scf
#      - the de Sitter conjecture s1=|dV|/V and -s2=d^2V/V
#      - the swampland conjecture 1+w-0.15s1^2
#      - the relative energy densities Omega_cdm = rho_cdm / rho_crit and Omega_scf = rho_scf / rho_crit


def _parse_background_column_labels(background_file: str) -> List[str]:
    """Parse the CLASS background header and return column labels in order."""
    header_line = None
    with open(background_file, "r") as f:
        for line in f:
            if line.startswith("#") and "1:z" in line:
                header_line = line.lstrip("#").strip()
                break

    if header_line is None:
        raise ValueError(
            f"Could not find CLASS background column header in: {background_file}"
        )

    # Capture chunks like "1:z", "2:proper time [Gyr]", ...
    matches = re.findall(r"(\d+):(.*?)(?=(?:\s+\d+:)|$)", header_line)
    if not matches:
        raise ValueError(f"Failed to parse header labels in: {background_file}")

    # Sort by index and strip text
    ordered = sorted(
        ((int(i), label.strip()) for i, label in matches), key=lambda x: x[0]
    )
    return [label for _, label in ordered]


def _find_column_index(labels: List[str], required_label: str) -> int:
    """Find exact column label index or raise a clear error."""
    try:
        return labels.index(required_label)
    except ValueError as exc:
        raise KeyError(
            f"Required background column '{required_label}' not found. Available labels: {labels}"
        ) from exc


def load_background_dataset(background_file: str) -> Dict[str, Any]:
    """Load CLASS background file, extract required columns, and compute derived quantities.

    Extracted columns:
      - z
      - (.)rho_cdm
      - (.)rho_scf
      - (.)rho_crit
      - (.)p_scf
      - V_scf
      - V'_scf
      - V''_scf

    Computed quantities:
      - a = 1/(1+z)
      - w = p_scf / rho_scf
      - s1 = |V'_scf| / V_scf
      - minus_s2 = V''_scf / V_scf
      - swampland_expr = 1 + w - 0.15 * s1^2
      - Omega_cdm = rho_cdm / rho_crit
      - Omega_scf = rho_scf / rho_crit
    """
    labels = _parse_background_column_labels(background_file)
    data = np.loadtxt(background_file, comments="#")

    if data.ndim == 1:
        data = data[np.newaxis, :]

    idx = {
        "z": _find_column_index(labels, "z"),
        "rho_cdm": _find_column_index(labels, "(.)rho_cdm"),
        "rho_scf": _find_column_index(labels, "(.)rho_scf"),
        "rho_crit": _find_column_index(labels, "(.)rho_crit"),
        "p_scf": _find_column_index(labels, "(.)p_scf"),
        "V": _find_column_index(labels, "V_scf"),
        "dV": _find_column_index(labels, "V'_scf"),
        "d2V": _find_column_index(labels, "V''_scf"),
    }

    z = data[:, idx["z"]]
    rho_cdm = data[:, idx["rho_cdm"]]
    rho_scf = data[:, idx["rho_scf"]]
    rho_crit = data[:, idx["rho_crit"]]
    p_scf = data[:, idx["p_scf"]]
    V = data[:, idx["V"]]
    dV = data[:, idx["dV"]]
    d2V = data[:, idx["d2V"]]

    with np.errstate(divide="ignore", invalid="ignore"):
        a = 1.0 / (1.0 + z)
        w = np.where(rho_scf != 0.0, p_scf / rho_scf, np.nan)
        s1 = np.where(V != 0.0, np.abs(dV) / V, np.nan)
        minus_s2 = np.where(V != 0.0, d2V / V, np.nan)
        swampland_expr = 1.0 + w - 0.15 * s1 * s1
        Omega_cdm = np.where(rho_crit != 0.0, rho_cdm / rho_crit, np.nan)
        Omega_scf = np.where(rho_crit != 0.0, rho_scf / rho_crit, np.nan)

    return {
        "background_file": background_file,
        "column_labels": labels,
        "column_indices": idx,
        "raw_table": data,
        "z": z,
        "a": a,
        "rho_cdm": rho_cdm,
        "rho_scf": rho_scf,
        "rho_crit": rho_crit,
        "p_scf": p_scf,
        "V": V,
        "dV": dV,
        "d2V": d2V,
        "w": w,
        "s1": s1,
        "minus_s2": minus_s2,
        "swampland_expr": swampland_expr,
        "Omega_cdm": Omega_cdm,
        "Omega_scf": Omega_scf,
    }


def save_background_dataset_cache(dataset: Dict[str, Any], cache_file: str) -> None:
    """Save processed background dataset to a compressed NPZ cache file."""
    path = Path(cache_file)
    path.parent.mkdir(parents=True, exist_ok=True)

    column_label_array = np.array(dataset["column_labels"], dtype=str)
    column_index_keys = np.array(list(dataset["column_indices"].keys()), dtype=str)
    column_index_values = np.array(
        list(dataset["column_indices"].values()), dtype=np.int64
    )

    np.savez_compressed(
        str(path),
        schema_version=np.array([1], dtype=np.int64),
        background_file=np.array([str(dataset["background_file"])], dtype=str),
        column_labels=column_label_array,
        column_index_keys=column_index_keys,
        column_index_values=column_index_values,
        raw_table=dataset["raw_table"],
        z=dataset["z"],
        a=dataset["a"],
        rho_cdm=dataset["rho_cdm"],
        rho_scf=dataset["rho_scf"],
        rho_crit=dataset["rho_crit"],
        p_scf=dataset["p_scf"],
        V=dataset["V"],
        dV=dataset["dV"],
        d2V=dataset["d2V"],
        w=dataset["w"],
        s1=dataset["s1"],
        minus_s2=dataset["minus_s2"],
        swampland_expr=dataset["swampland_expr"],
        Omega_cdm=dataset["Omega_cdm"],
        Omega_scf=dataset["Omega_scf"],
    )


def load_background_dataset_cache(cache_file: str) -> Dict[str, Any]:
    """Load processed background dataset from a compressed NPZ cache file."""
    with np.load(cache_file, allow_pickle=False) as cached:
        schema_version = int(cached["schema_version"][0])
        if schema_version != 1:
            raise ValueError(
                f"Unsupported background cache schema version: {schema_version}"
            )

        column_labels = [str(x) for x in cached["column_labels"].tolist()]
        column_index_keys = [str(x) for x in cached["column_index_keys"].tolist()]
        column_index_values = [int(x) for x in cached["column_index_values"].tolist()]
        column_indices = dict(zip(column_index_keys, column_index_values))

        return {
            "background_file": str(cached["background_file"][0]),
            "column_labels": column_labels,
            "column_indices": column_indices,
            "raw_table": cached["raw_table"],
            "z": cached["z"],
            "a": cached["a"],
            "rho_cdm": cached["rho_cdm"],
            "rho_scf": cached["rho_scf"],
            "rho_crit": cached["rho_crit"],
            "p_scf": cached["p_scf"],
            "V": cached["V"],
            "dV": cached["dV"],
            "d2V": cached["d2V"],
            "w": cached["w"],
            "s1": cached["s1"],
            "minus_s2": cached["minus_s2"],
            "swampland_expr": cached["swampland_expr"],
            "Omega_cdm": cached["Omega_cdm"],
            "Omega_scf": cached["Omega_scf"],
        }


def load_or_compute_background_dataset(
    background_file: str,
    cache_file: Optional[str] = None,
) -> Tuple[Dict[str, Any], str]:
    """Load processed dataset from cache when valid; otherwise compute and cache.

    Returns:
        (dataset, source) where source is one of: "cache" or "computed".
    """
    if cache_file is None:
        cache_file = str(Path(background_file).with_suffix(".processed.npz"))

    bg_path = Path(background_file)
    cache_path = Path(cache_file)

    if cache_path.exists() and cache_path.stat().st_mtime >= bg_path.stat().st_mtime:
        dataset = load_background_dataset_cache(str(cache_path))
        return dataset, "cache"

    dataset = load_background_dataset(background_file)
    save_background_dataset_cache(dataset, str(cache_path))
    return dataset, "computed"


if __name__ == "__main__":
    """Main entry point for command-line execution."""
    args = parse_arguments()

    try:
        # Extract parameters
        class_params, metadata = extract_parameters_from_bestfit(args.bestfit_file)

        # Display step 1 results
        print("\n" + "=" * 80)
        print("CLASS Parameters Extracted Successfully")
        print("=" * 80)
        print(f"\nBest-fit file:    {metadata['bestfit_file']}")
        print(f"YAML config file: {metadata['yaml_file']}")
        print(f"Parameters extracted: {metadata['parameters_extracted']}")

        if metadata["warnings"]:
            print("\nWarnings:")
            for warning in metadata["warnings"]:
                print(f"  ⚠ {warning}")

        print("\n" + "-" * 80)
        print("CLASS Input Parameters (ready for classy.set()):")
        print("-" * 80)

        # Sort and display parameters
        for key in sorted(class_params.keys()):
            value = class_params[key]
            # Format the value nicely
            if isinstance(value, float):
                print(f"  {key:30s} = {value:.15g}")
            elif isinstance(value, str):
                print(f"  {key:30s} = {value}")
            else:
                print(f"  {key:30s} = {value}")

        print("\n" + "=" * 80)
        print("Full dictionary for classy.set():")
        print("=" * 80)
        print(repr(class_params))

        # Step 2: Run CLASS and generate background output file (or reuse existing one)
        print("\n" + "=" * 80)
        print("Running CLASS To Generate Background Evolution")
        print("=" * 80)
        run_label = Path(args.bestfit_file).name.replace(".bestfit", "")
        output_root = Path(args.output_dir).expanduser().resolve() / run_label
        background_file = Path(f"{output_root}_background.dat")

        if args.reuse_background:
            if not background_file.exists():
                raise FileNotFoundError(
                    f"--reuse_background was set but background file does not exist: {background_file}"
                )
            run_info = {
                "class_executable": str(Path(__file__).resolve().parents[1] / "class"),
                "generated_ini": "(reused)",
                "output_root": str(output_root),
                "background_file": str(background_file),
            }
            print("CLASS run skipped: reusing existing background output.")
            print(f"Output root:      {run_info['output_root']}")
            print(f"Background file:  {run_info['background_file']}")
        else:
            run_info = run_class_background(
                class_params=class_params,
                bestfit_path=args.bestfit_file,
                output_dir=args.output_dir,
            )
            print(f"CLASS executable: {run_info['class_executable']}")
            print(f"Generated ini:    {run_info['generated_ini']}")
            print(f"Output root:      {run_info['output_root']}")
            print(f"Background file:  {run_info['background_file']}")
            print(
                "\nBackground extraction completed. This file can now be loaded for plotting."
            )

        # Step 2.b: Load background file and compute quantities for plotting.
        cache_file = str(
            Path(run_info["background_file"]).with_suffix(".processed.npz")
        )
        background_dataset, dataset_source = load_or_compute_background_dataset(
            background_file=run_info["background_file"],
            cache_file=cache_file,
        )
        print("\n" + "=" * 80)
        print("Background Data Loaded And Processed")
        print("=" * 80)
        print(f"Data source:      {dataset_source}")
        print(f"Cache file:       {cache_file}")
        print(f"Rows loaded:      {background_dataset['raw_table'].shape[0]}")
        print(f"Columns loaded:   {background_dataset['raw_table'].shape[1]}")
        print(
            "Stored arrays:    "
            "z, a, rho_cdm, rho_scf, rho_crit, p_scf, V, dV, d2V, w, s1, minus_s2, "
            "swampland_expr, Omega_cdm, Omega_scf"
        )
        print(
            f"z-range:          [{np.nanmin(background_dataset['z']):.6g}, {np.nanmax(background_dataset['z']):.6g}]"
        )

        # Pass runtime context to the plotting stage implemented at file bottom.
        globals()["_BESTFITPLOT_RUNTIME"] = {
            "background_dataset": background_dataset,
            "output_root": str(output_root),
        }

        # Note about next steps
        print("\n" + "*" * 80)
        print("Next step: Build publication-quality plots:")
        print("*" * 80)
        print("""
    # Plots are generated automatically at the end of this script.
    # Use --reuse_background to skip rerunning CLASS while iterating on style.
        """)

    except FileNotFoundError as e:
        print(f"❌ Error: {e}", file=sys.stderr)
        sys.exit(1)
    except ValueError as e:
        print(f"❌ Validation Error: {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"❌ Unexpected Error: {e}", file=sys.stderr)
        import traceback

        traceback.print_exc()
        sys.exit(1)


# 3. Plot the results
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.ticker import FixedFormatter, FixedLocator, NullFormatter

_HIGH_CONTRAST_PALETTE: Dict[str, str] = {
    "black": "#000000",
    "blue": "#004488",
    "red": "#BB5566",
    "yellow": "#DDAA33",
    "white": "#FFFFFF",
}

mpl.rcParams.update(
    {
        "font.family": "serif",  # Computer Modern — the default LaTeX font
        "font.size": 9.5,  # slightly lighter page color in print while staying legible
        "axes.labelsize": 10,
        "xtick.labelsize": 9,
        "ytick.labelsize": 9,
        "legend.fontsize": 9,
        "lines.linewidth": 1.35,  # balance curve emphasis against grid and frame
        "axes.linewidth": 0.75,
        "xtick.direction": "in",  # inward ticks — journal standard
        "ytick.direction": "in",
        "xtick.minor.visible": True,  # show minor ticks
        "ytick.minor.visible": True,
        "xtick.major.size": 4,  # longer than the 3.5 default
        "ytick.major.size": 4,
        "xtick.minor.size": 2,  # half of major — proportional
        "ytick.minor.size": 2,
        "xtick.major.width": 0.75,
        "ytick.major.width": 0.75,
        "xtick.minor.width": 0.55,
        "ytick.minor.width": 0.55,
        "lines.markersize": 4,  # smaller markers for print scale
        "errorbar.capsize": 3,  # visible end-caps (default is 0)
        "axes.xmargin": 0.02,  # hug the data (default is 0.05)
        "axes.ymargin": 0.02,
        "legend.frameon": False,  # no legend box
        "savefig.bbox": "tight",  # tight bounding box by default
        "savefig.dpi": 300,  # publication-quality resolution
        **(  # LaTeX if installed, else fallback
            {
                "text.usetex": True,  # real LaTeX for all text
                "pgf.preamble": (
                    r"\usepackage{fontspec}"
                    r"\usepackage{mathtools}"
                    r"\usepackage{amsfonts}"
                    r"\usepackage{amssymb}"
                    r"\usepackage[warnings-off={mathtools-overbracket,mathtools-colon}]{unicode-math}"
                    r"\setmainfont{IBM Plex Serif}"
                    r"\setsansfont{IBM Plex Sans}"
                    r"\setmonofont{IBM Plex Mono}"
                    r"\setmathfont{IBM Plex Math}"
                ),
                "text.latex.preamble": r"\usepackage{amsfonts}\usepackage{amssymb}",
                "pgf.texsystem": "lualatex",  # consistent PGF export
                "pgf.rcfonts": False,
            }  # let LaTeX control fonts
            if __import__("shutil").which("latex")
            else {
                "text.usetex": False,  # no TeX install found
                "mathtext.fontset": "cm",
            }  # Computer Modern via mathtext
        ),
    }
)


def _prepare_plot_arrays(background_dataset: Dict[str, Any]) -> Dict[str, np.ndarray]:
    """Prepare sorted plotting arrays and derived series used in all figures."""
    z = np.asarray(background_dataset["z"], dtype=float)
    order = np.argsort(z)

    z_plot = z[order]
    s1 = np.asarray(background_dataset["s1"], dtype=float)[order]
    # Convention: dataset stores minus_s2 = V''/V, so s2 = -V''/V = -minus_s2.
    s2 = -np.asarray(background_dataset["minus_s2"], dtype=float)[order]
    omega_scf = np.asarray(background_dataset["Omega_scf"], dtype=float)[order]
    omega_cdm = np.asarray(background_dataset["Omega_cdm"], dtype=float)[order]
    w = np.asarray(background_dataset["w"], dtype=float)[order]
    swampland_expr = np.asarray(background_dataset["swampland_expr"], dtype=float)[
        order
    ]

    return {
        "z": z_plot,
        "s1": s1,
        "s2": s2,
        "Omega_scf": omega_scf,
        "Omega_cdm": omega_cdm,
        "w": w,
        "swampland_expr": swampland_expr,
    }


def _style_redshift_axis(ax: plt.Axes, z: np.ndarray) -> None:
    """Apply consistent redshift-axis styling with z=0 at the right side."""
    finite_z = z[np.isfinite(z)]
    zmax = float(np.nanmax(finite_z)) if finite_z.size else 1.0

    # Symlog preserves visibility near z=0 while handling the full cosmic range.
    ax.set_xscale("symlog", linthresh=1.0)
    ax.set_xlim(zmax, 0.0)

    # Publication-oriented tick design: explicit decade majors plus a terminal 0,
    # and sparse decade minors (2 and 5) for cleaner density.
    if zmax >= 1.0:
        max_pow = int(np.floor(np.log10(zmax)))
        major_ticks = [10.0**p for p in range(max_pow, -1, -1)] + [0.0]
    else:
        major_ticks = [zmax, 0.0]

    major_ticks = sorted(set(float(t) for t in major_ticks))

    major_labels = []
    for t in major_ticks:
        if np.isclose(t, 0.0):
            major_labels.append("0")
        elif t >= 1.0:
            p = int(np.round(np.log10(t)))
            major_labels.append(rf"$10^{{{p}}}$")
        else:
            major_labels.append("")
    ax.xaxis.set_major_locator(FixedLocator(major_ticks))
    ax.xaxis.set_major_formatter(FixedFormatter(major_labels))

    minor_ticks = []
    if zmax >= 10.0:
        for p in range(max_pow - 1, -1, -1):
            d = 10.0**p
            for m in (2, 5):
                t = m * d
                if 1.0 < t < zmax:
                    minor_ticks.append(t)

    # Keep a minimal set of linear-region minor ticks near z~0.
    minor_ticks.extend([0.2, 0.4, 0.6, 0.8])
    minor_ticks = sorted(set(minor_ticks))
    ax.xaxis.set_minor_locator(FixedLocator(minor_ticks))
    ax.xaxis.set_minor_formatter(NullFormatter())

    ax.set_xlabel(r"Redshift $z$")
    ax.grid(True, which="major", alpha=0.25, linewidth=0.6)
    ax.grid(True, which="minor", alpha=0.12, linewidth=0.4)


def _save_figure_bundle(fig: plt.Figure, base_path: Path) -> None:
    """Save each figure as PNG/PDF/PGF for quick view and publication workflows."""
    fig.savefig(str(base_path.with_suffix(".png")))
    fig.savefig(str(base_path.with_suffix(".pdf")))
    fig.savefig(str(base_path.with_suffix(".pgf")))


def _apply_tight_ylims(
    ax: plt.Axes,
    arrays: List[np.ndarray],
    pad_frac: float = 0.08,
) -> None:
    """Set robust y-limits with small padding for publication-ready hierarchy."""
    finite_chunks = [a[np.isfinite(a)] for a in arrays]
    finite_chunks = [a for a in finite_chunks if a.size > 0]
    if not finite_chunks:
        return

    y_all = np.concatenate(finite_chunks)
    y_lo = float(np.nanmin(y_all))
    y_hi = float(np.nanmax(y_all))

    if not np.isfinite(y_lo) or not np.isfinite(y_hi):
        return

    span = y_hi - y_lo
    if span <= 0.0:
        # Nearly constant curve: enforce a symmetric micro-window around value.
        center = y_lo
        eps = max(1e-6, abs(center) * 0.02)
        ax.set_ylim(center - eps, center + eps)
        return

    pad = span * pad_frac
    ax.set_ylim(y_lo - pad, y_hi + pad)


def make_three_plots(
    background_dataset: Dict[str, Any], output_root: str
) -> Dict[str, str]:
    """Create the three requested polished science plots and save them to disk."""
    series = _prepare_plot_arrays(background_dataset)
    z = series["z"]

    out_root = Path(output_root)
    out_dir = out_root.parent
    stem = out_root.name
    out_dir.mkdir(parents=True, exist_ok=True)

    c1 = _HIGH_CONTRAST_PALETTE["blue"]
    c2 = _HIGH_CONTRAST_PALETTE["yellow"]
    c3 = _HIGH_CONTRAST_PALETTE["red"]
    c4 = _HIGH_CONTRAST_PALETTE["black"]

    ls_primary = "-"
    ls_secondary = "--"

    legend_kw = {
        "loc": "lower left",
        "bbox_to_anchor": (0.02, 0.06),
        "handlelength": 2.2,
        "labelspacing": 0.35,
        "borderaxespad": 0.0,
    }

    # Plot 1: de Sitter conjecture parameters s1 and s2.
    fig1, ax1 = plt.subplots(figsize=(6.4, 4.1))
    ax1.plot(
        z,
        series["s1"],
        color=c1,
        linestyle=ls_primary,
        label=r"$\mathfrak{s}_1 = |V_{\phi}|/V$",
    )
    ax1.plot(
        z,
        series["s2"],
        color=c2,
        linestyle=ls_secondary,
        label=r"$\mathfrak{s}_2 = -V_{\phi\phi}/V$",
    )
    _style_redshift_axis(ax1, z)
    _apply_tight_ylims(ax1, [series["s1"], series["s2"]], pad_frac=0.04)
    ax1.set_ylabel(r"de Sitter Parameters")
    ax1.legend(**legend_kw)
    fig1.tight_layout()
    p1 = out_dir / f"{stem}_plot1_ds"
    _save_figure_bundle(fig1, p1)
    plt.close(fig1)

    # Plot 2: Omega_scf and Omega_cdm.
    fig2, ax2 = plt.subplots(figsize=(6.4, 4.1))
    ax2.plot(
        z,
        series["Omega_scf"],
        color=c3,
        linestyle=ls_primary,
        label=r"$\Omega_{\mathrm{scf}}$",
    )
    ax2.plot(
        z,
        series["Omega_cdm"],
        color=c4,
        linestyle=ls_secondary,
        label=r"$\Omega_{\mathrm{cdm}}$",
    )
    _style_redshift_axis(ax2, z)
    _apply_tight_ylims(ax2, [series["Omega_scf"], series["Omega_cdm"]], pad_frac=0.035)
    ax2.set_ylabel(r"Relative Energy Density")
    ax2.legend(**legend_kw)
    fig2.tight_layout()
    p2 = out_dir / f"{stem}_plot2_omegas"
    _save_figure_bundle(fig2, p2)
    plt.close(fig2)

    # Plot 3: swampland expression and w, plus horizontal y=0 and y=-1 references.
    fig3, ax3 = plt.subplots(figsize=(6.4, 4.1))
    ax3.plot(
        z,
        series["swampland_expr"],
        color=c2,
        linestyle=ls_secondary,
        label=r"$1+w-0.15\,\mathfrak{s}_1^2$",
    )
    ax3.plot(z, series["w"], color=c1, linestyle=ls_primary, label=r"$w$")
    ax3.axhline(
        0.0, color="0.20", linestyle=(0, (5, 2.5)), linewidth=1.0, alpha=0.9, zorder=1
    )
    ax3.axhline(
        -1.0,
        color="0.35",
        linestyle=(0, (1.2, 2.0)),
        linewidth=1.0,
        alpha=0.85,
        zorder=1,
    )
    _style_redshift_axis(ax3, z)
    _apply_tight_ylims(ax3, [series["swampland_expr"], series["w"]], pad_frac=0.05)
    ax3.set_ylabel(r"Equation of State")
    ax3.legend(**legend_kw)
    fig3.tight_layout()
    p3 = out_dir / f"{stem}_plot3_swampland_w"
    _save_figure_bundle(fig3, p3)
    plt.close(fig3)

    return {
        "plot1_png": str(p1.with_suffix(".png")),
        "plot1_pdf": str(p1.with_suffix(".pdf")),
        "plot1_pgf": str(p1.with_suffix(".pgf")),
        "plot2_png": str(p2.with_suffix(".png")),
        "plot2_pdf": str(p2.with_suffix(".pdf")),
        "plot2_pgf": str(p2.with_suffix(".pgf")),
        "plot3_png": str(p3.with_suffix(".png")),
        "plot3_pdf": str(p3.with_suffix(".pdf")),
        "plot3_pgf": str(p3.with_suffix(".pgf")),
    }


if __name__ == "__main__" and "_BESTFITPLOT_RUNTIME" in globals():
    _runtime = globals()["_BESTFITPLOT_RUNTIME"]
    _plot_paths = make_three_plots(
        background_dataset=_runtime["background_dataset"],
        output_root=_runtime["output_root"],
    )

    print("\n" + "=" * 80)
    print("Plots Generated")
    print("=" * 80)
    for _name, _path in _plot_paths.items():
        print(f"{_name:10s}: {_path}")
